import type { ChecklistTemplate } from './types'

export const aiTemplates: ChecklistTemplate[] = [
  {
    id: 'tpl-prompt-engineering',
    name: 'Prompt Engineering Workflow',
    description: 'Systematic checklist for designing, testing, and iterating on LLM prompts for production use.',
    category: 'ai',
    mode: 'advanced',
    tags: ['prompt engineering', 'llm', 'ai', 'gpt'],
    featured: true,
    previewLines: ['Design', 'Define task and desired output format', 'Test', 'Run against edge cases and adversarial inputs'],
    items: [
      { id: 'pe1',  text: 'Design',                                           state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'pe2',  text: 'Define the exact task in one sentence',            state: 'unchecked', depth: 1, parentId: 'pe1', collapsed: false },
      { id: 'pe3',  text: 'Specify desired output format (JSON, markdown…)',  state: 'unchecked', depth: 1, parentId: 'pe1', collapsed: false },
      { id: 'pe4',  text: 'Add role / persona context to system prompt',      state: 'unchecked', depth: 1, parentId: 'pe1', collapsed: false },
      { id: 'pe5',  text: 'Include 2–3 few-shot examples',                   state: 'unchecked', depth: 1, parentId: 'pe1', collapsed: false },
      { id: 'pe6',  text: 'Add explicit constraints (length, tone, scope)',   state: 'unchecked', depth: 1, parentId: 'pe1', collapsed: false },
      { id: 'pe7',  text: 'Test',                                             state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'pe8',  text: 'Run 10+ varied inputs to check consistency',      state: 'unchecked', depth: 1, parentId: 'pe7', collapsed: false },
      { id: 'pe9',  text: 'Test adversarial and edge-case inputs',           state: 'unchecked', depth: 1, parentId: 'pe7', collapsed: false },
      { id: 'pe10', text: 'Compare outputs across temperature settings',      state: 'unchecked', depth: 1, parentId: 'pe7', collapsed: false },
      { id: 'pe11', text: 'Evaluate with human or LLM-as-judge scoring',    state: 'unchecked', depth: 1, parentId: 'pe7', collapsed: false },
      { id: 'pe12', text: 'Production',                                      state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'pe13', text: 'Prompt versioned and stored in source control',   state: 'unchecked', depth: 1, parentId: 'pe12', collapsed: false },
      { id: 'pe14', text: 'Token cost per call estimated and acceptable',    state: 'unchecked', depth: 1, parentId: 'pe12', collapsed: false },
      { id: 'pe15', text: 'Fallback behaviour defined for model errors',     state: 'unchecked', depth: 1, parentId: 'pe12', collapsed: false },
      { id: 'pe16', text: 'Output validation / guardrails implemented',      state: 'unchecked', depth: 1, parentId: 'pe12', collapsed: false },
    ],
  },
  {
    id: 'tpl-ai-feature-ship',
    name: 'AI Feature Readiness',
    description: 'Pre-ship checklist for AI-powered features covering accuracy, cost, safety, and observability.',
    category: 'ai',
    mode: 'simple',
    tags: ['ai', 'llm', 'feature', 'production'],
    featured: false,
    previewLines: ['Accuracy baseline measured on eval dataset', 'Hallucination rate acceptable for use case', 'Cost per user request within budget', 'Rate limiting and abuse prevention in place'],
    items: [
      { id: 'af1',  text: 'Accuracy baseline measured on representative eval set', state: 'unchecked' },
      { id: 'af2',  text: 'Hallucination rate acceptable for use case',           state: 'unchecked' },
      { id: 'af3',  text: 'Latency P95 within acceptable UX threshold',           state: 'unchecked' },
      { id: 'af4',  text: 'Cost per request estimated and within budget',          state: 'unchecked' },
      { id: 'af5',  text: 'Rate limiting per user implemented',                    state: 'unchecked' },
      { id: 'af6',  text: 'Input length limits enforced (token budget)',           state: 'unchecked' },
      { id: 'af7',  text: 'Output moderation / content filtering in place',        state: 'unchecked' },
      { id: 'af8',  text: 'PII not sent to third-party model API',                state: 'unchecked' },
      { id: 'af9',  text: 'Streaming or timeout fallback handled gracefully',      state: 'unchecked' },
      { id: 'af10', text: 'Model provider uptime dependency documented',           state: 'unchecked' },
      { id: 'af11', text: 'User-facing "AI-generated" disclosure present',        state: 'unchecked' },
      { id: 'af12', text: 'Logging of inputs/outputs for debugging (privacy-safe)', state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-ai-project-kickoff',
    name: 'AI Project Kickoff',
    description: 'Structured checklist for kicking off an ML/AI project from problem definition to first model iteration.',
    category: 'ai',
    mode: 'advanced',
    tags: ['machine learning', 'ai', 'project', 'data science'],
    featured: false,
    previewLines: ['Problem Definition', 'Business metric tied to ML metric', 'Data', 'Training and test splits defined'],
    items: [
      { id: 'ak1',  text: 'Problem Definition',                                  state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ak2',  text: 'Business objective and success metric agreed',        state: 'unchecked', depth: 1, parentId: 'ak1', collapsed: false },
      { id: 'ak3',  text: 'ML framing decided (classification, regression…)',    state: 'unchecked', depth: 1, parentId: 'ak1', collapsed: false },
      { id: 'ak4',  text: 'Baseline (rules-based or human) performance known',  state: 'unchecked', depth: 1, parentId: 'ak1', collapsed: false },
      { id: 'ak5',  text: 'Data',                                                state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ak6',  text: 'Data sources identified and access confirmed',        state: 'unchecked', depth: 1, parentId: 'ak5', collapsed: false },
      { id: 'ak7',  text: 'Data volume sufficient for task estimated',           state: 'unchecked', depth: 1, parentId: 'ak5', collapsed: false },
      { id: 'ak8',  text: 'Train / validation / test splits defined',            state: 'unchecked', depth: 1, parentId: 'ak5', collapsed: false },
      { id: 'ak9',  text: 'Data labelling approach agreed',                      state: 'unchecked', depth: 1, parentId: 'ak5', collapsed: false },
      { id: 'ak10', text: 'Modelling',                                           state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ak11', text: 'Experiment tracking tool set up (MLflow / W&B)',      state: 'unchecked', depth: 1, parentId: 'ak10', collapsed: false },
      { id: 'ak12', text: 'Evaluation metric(s) agreed and implemented',        state: 'unchecked', depth: 1, parentId: 'ak10', collapsed: false },
      { id: 'ak13', text: 'First simple model run as sanity check',             state: 'unchecked', depth: 1, parentId: 'ak10', collapsed: false },
    ],
  },
  {
    id: 'tpl-llm-evaluation',
    name: 'LLM Model Evaluation',
    description: 'Checklist for rigorously evaluating and comparing large language model outputs before deployment.',
    category: 'ai',
    mode: 'simple',
    tags: ['llm', 'evaluation', 'benchmark', 'ai'],
    featured: false,
    previewLines: ['Eval dataset covers diverse real-world inputs', 'Automated metrics defined (BLEU, ROUGE, custom)', 'Human eval sample size statistically significant', 'Failure modes catalogued and documented'],
    items: [
      { id: 'le1',  text: 'Eval dataset covers diverse, real-world input types',   state: 'unchecked' },
      { id: 'le2',  text: 'Golden reference answers created or sourced',           state: 'unchecked' },
      { id: 'le3',  text: 'Automated metrics selected and justified',              state: 'unchecked' },
      { id: 'le4',  text: 'Human eval rubric defined (1–5 scale with criteria)',   state: 'unchecked' },
      { id: 'le5',  text: 'Sample size statistically meaningful (n ≥ 100)',        state: 'unchecked' },
      { id: 'le6',  text: 'Evaluated across model sizes / providers for cost',     state: 'unchecked' },
      { id: 'le7',  text: 'Edge cases and adversarial inputs included in eval',    state: 'unchecked' },
      { id: 'le8',  text: 'Latency and cost per call benchmarked',                 state: 'unchecked' },
      { id: 'le9',  text: 'Failure modes catalogued with example outputs',        state: 'unchecked' },
      { id: 'le10', text: 'Results documented and shared with stakeholders',       state: 'unchecked' },
    ],
  },
]
