import type { ChecklistTemplate } from './types'

export const businessTemplates: ChecklistTemplate[] = [
  {
    id: 'tpl-client-onboarding',
    name: 'Client Onboarding',
    description: 'Structured client onboarding checklist to set expectations and deliver a great first impression.',
    category: 'business',
    mode: 'advanced',
    tags: ['client', 'onboarding', 'customer success', 'b2b'],
    featured: false,
    previewLines: ['Pre-Start', 'Contract and NDA signed', 'Week 1', 'Goals and success metrics agreed'],
    items: [
      { id: 'co1',  text: 'Pre-Start',                                     state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'co2',  text: 'Contract and NDA signed',                       state: 'unchecked', depth: 1, parentId: 'co1', collapsed: false },
      { id: 'co3',  text: 'Invoice or payment schedule confirmed',         state: 'unchecked', depth: 1, parentId: 'co1', collapsed: false },
      { id: 'co4',  text: 'Welcome email sent with next steps',            state: 'unchecked', depth: 1, parentId: 'co1', collapsed: false },
      { id: 'co5',  text: 'Kickoff call scheduled',                        state: 'unchecked', depth: 1, parentId: 'co1', collapsed: false },
      { id: 'co6',  text: 'Kickoff Call',                                  state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'co7',  text: 'Business goals and success metrics agreed',     state: 'unchecked', depth: 1, parentId: 'co6', collapsed: false },
      { id: 'co8',  text: 'Communication cadence agreed',                  state: 'unchecked', depth: 1, parentId: 'co6', collapsed: false },
      { id: 'co9',  text: 'Point of contact on each side confirmed',       state: 'unchecked', depth: 1, parentId: 'co6', collapsed: false },
      { id: 'co10', text: 'Deliverables and timeline reviewed together',   state: 'unchecked', depth: 1, parentId: 'co6', collapsed: false },
      { id: 'co11', text: 'Setup',                                         state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'co12', text: 'Access and credentials shared securely',        state: 'unchecked', depth: 1, parentId: 'co11', collapsed: false },
      { id: 'co13', text: 'Project management tool / shared workspace set up', state: 'unchecked', depth: 1, parentId: 'co11', collapsed: false },
      { id: 'co14', text: '30-day check-in scheduled in calendar',         state: 'unchecked', depth: 1, parentId: 'co11', collapsed: false },
    ],
  },
  {
    id: 'tpl-business-plan-review',
    name: 'Business Plan Review',
    description: 'Checklist for reviewing a business plan for completeness, realism, and investor-readiness.',
    category: 'business',
    mode: 'simple',
    tags: ['business plan', 'strategy', 'review', 'planning'],
    featured: false,
    previewLines: ['Executive summary is compelling in under 2 pages', 'Market size has credible sources', 'Revenue model is clearly explained', 'Assumptions are listed and defensible'],
    items: [
      { id: 'bp1',  text: 'Executive summary is compelling and under 2 pages',   state: 'unchecked' },
      { id: 'bp2',  text: 'Problem and solution clearly defined',                 state: 'unchecked' },
      { id: 'bp3',  text: 'Market size credibly sourced (not just Google)',       state: 'unchecked' },
      { id: 'bp4',  text: 'Target customer segment specific and researchable',   state: 'unchecked' },
      { id: 'bp5',  text: 'Revenue model clearly explained',                      state: 'unchecked' },
      { id: 'bp6',  text: 'Unit economics (CAC, LTV, payback) included',         state: 'unchecked' },
      { id: 'bp7',  text: 'Competitive analysis is honest and differentiated',   state: 'unchecked' },
      { id: 'bp8',  text: 'Financial projections have explicit assumptions',      state: 'unchecked' },
      { id: 'bp9',  text: 'Break-even point identified',                          state: 'unchecked' },
      { id: 'bp10', text: 'Key risks and mitigation strategies included',         state: 'unchecked' },
      { id: 'bp11', text: 'Team section shows relevant experience',               state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-hiring-process',
    name: 'Hiring Process',
    description: 'Structured hiring checklist from job post to offer letter for consistent, bias-reduced recruitment.',
    category: 'business',
    mode: 'advanced',
    tags: ['hiring', 'recruitment', 'hr', 'interview'],
    featured: false,
    previewLines: ['Job Post', 'Requirements separated from nice-to-haves', 'Interview', 'Scorecard agreed before first interview'],
    items: [
      { id: 'hp1',  text: 'Job Post',                                       state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'hp2',  text: 'Must-haves separated from nice-to-haves',        state: 'unchecked', depth: 1, parentId: 'hp1', collapsed: false },
      { id: 'hp3',  text: 'Salary range included in posting',               state: 'unchecked', depth: 1, parentId: 'hp1', collapsed: false },
      { id: 'hp4',  text: 'Job posted on relevant platforms',               state: 'unchecked', depth: 1, parentId: 'hp1', collapsed: false },
      { id: 'hp5',  text: 'Screen',                                         state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'hp6',  text: 'CV screen against must-have criteria only',      state: 'unchecked', depth: 1, parentId: 'hp5', collapsed: false },
      { id: 'hp7',  text: 'Async intro questions sent to shortlist',        state: 'unchecked', depth: 1, parentId: 'hp5', collapsed: false },
      { id: 'hp8',  text: 'Interview',                                      state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'hp9',  text: 'Scorecard agreed before first interview',        state: 'unchecked', depth: 1, parentId: 'hp8', collapsed: false },
      { id: 'hp10', text: 'Structured questions used consistently',         state: 'unchecked', depth: 1, parentId: 'hp8', collapsed: false },
      { id: 'hp11', text: 'Take-home or technical task sent',               state: 'unchecked', depth: 1, parentId: 'hp8', collapsed: false },
      { id: 'hp12', text: 'Reference checks completed',                     state: 'unchecked', depth: 1, parentId: 'hp8', collapsed: false },
      { id: 'hp13', text: 'Offer',                                          state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'hp14', text: 'Offer letter sent within 24h of decision',       state: 'unchecked', depth: 1, parentId: 'hp13', collapsed: false },
      { id: 'hp15', text: 'Onboarding plan shared on acceptance',           state: 'unchecked', depth: 1, parentId: 'hp13', collapsed: false },
    ],
  },
  {
    id: 'tpl-board-meeting-prep',
    name: 'Board Meeting Prep',
    description: 'Pre-board meeting preparation checklist to ensure a productive, well-structured session.',
    category: 'business',
    mode: 'simple',
    tags: ['board meeting', 'governance', 'executive', 'startup'],
    featured: false,
    previewLines: ['Board pack sent 5 days before meeting', 'Financial highlights compared to plan', 'Key decisions clearly framed with options', 'Action items from last meeting reviewed'],
    items: [
      { id: 'bm1',  text: 'Board pack sent at least 5 days before meeting',      state: 'unchecked' },
      { id: 'bm2',  text: 'Financial highlights vs plan included',                state: 'unchecked' },
      { id: 'bm3',  text: 'KPIs with trend vs last quarter included',            state: 'unchecked' },
      { id: 'bm4',  text: 'Key risks flagged proactively',                       state: 'unchecked' },
      { id: 'bm5',  text: 'Decisions requiring board approval clearly framed',   state: 'unchecked' },
      { id: 'bm6',  text: 'Each decision presented with options and recommendation', state: 'unchecked' },
      { id: 'bm7',  text: 'Action items from last meeting reviewed',              state: 'unchecked' },
      { id: 'bm8',  text: 'Agenda distributed with time allocations',            state: 'unchecked' },
      { id: 'bm9',  text: 'Board minutes from last meeting approved',            state: 'unchecked' },
      { id: 'bm10', text: 'CEO/CFO pre-aligned on key messages before meeting', state: 'unchecked' },
    ],
  },
]
