import type { ChecklistTemplate } from './types'

export const contentTemplates: ChecklistTemplate[] = [
  {
    id: 'tpl-youtube-publish',
    name: 'YouTube Publishing Workflow',
    description: 'End-to-end YouTube video publishing checklist from final edit to post-publish optimisation.',
    category: 'content',
    mode: 'advanced',
    tags: ['youtube', 'video', 'content creation', 'publishing'],
    featured: true,
    previewLines: ['Pre-Upload', 'Thumbnail designed and A/B option ready', 'Upload', 'End screen and cards added'],
    items: [
      { id: 'yt1',  text: 'Pre-Upload',                                      state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'yt2',  text: 'Video exported at 1080p or 4K, H.264',           state: 'unchecked', depth: 1, parentId: 'yt1', collapsed: false },
      { id: 'yt3',  text: 'Thumbnail created (1280×720, high contrast)',     state: 'unchecked', depth: 1, parentId: 'yt1', collapsed: false },
      { id: 'yt4',  text: 'A/B thumbnail variant ready',                    state: 'unchecked', depth: 1, parentId: 'yt1', collapsed: false },
      { id: 'yt5',  text: 'Title contains target keyword',                  state: 'unchecked', depth: 1, parentId: 'yt1', collapsed: false },
      { id: 'yt6',  text: 'Description: keyword-rich first 2 lines',        state: 'unchecked', depth: 1, parentId: 'yt1', collapsed: false },
      { id: 'yt7',  text: 'Upload',                                          state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'yt8',  text: 'Tags added (10–15 relevant terms)',               state: 'unchecked', depth: 1, parentId: 'yt7', collapsed: false },
      { id: 'yt9',  text: 'Category and language set correctly',             state: 'unchecked', depth: 1, parentId: 'yt7', collapsed: false },
      { id: 'yt10', text: 'End screen and cards pointing to next video',     state: 'unchecked', depth: 1, parentId: 'yt7', collapsed: false },
      { id: 'yt11', text: 'Chapters added in description (00:00 format)',   state: 'unchecked', depth: 1, parentId: 'yt7', collapsed: false },
      { id: 'yt12', text: 'Captions uploaded or auto-captions corrected',   state: 'unchecked', depth: 1, parentId: 'yt7', collapsed: false },
      { id: 'yt13', text: 'Promotion',                                       state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'yt14', text: 'Posted to community tab and social channels',    state: 'unchecked', depth: 1, parentId: 'yt13', collapsed: false },
      { id: 'yt15', text: 'Pinned comment added with key links',            state: 'unchecked', depth: 1, parentId: 'yt13', collapsed: false },
      { id: 'yt16', text: 'Replied to first 20 comments within 2 hours',   state: 'unchecked', depth: 1, parentId: 'yt13', collapsed: false },
    ],
  },
  {
    id: 'tpl-podcast-episode',
    name: 'Podcast Episode Publish',
    description: 'Production-to-publish checklist for releasing a podcast episode across all platforms.',
    category: 'content',
    mode: 'simple',
    tags: ['podcast', 'audio', 'publishing', 'content'],
    featured: false,
    previewLines: ['Audio edited and noise removed', 'Intro and outro music added', 'Show notes written with timestamps', 'Episode submitted to RSS feed'],
    items: [
      { id: 'pp1',  text: 'Audio edited — filler words and long pauses removed', state: 'unchecked' },
      { id: 'pp2',  text: 'Noise reduction applied',                              state: 'unchecked' },
      { id: 'pp3',  text: 'Levels normalised (target -16 LUFS for podcasts)',    state: 'unchecked' },
      { id: 'pp4',  text: 'Intro and outro music added',                          state: 'unchecked' },
      { id: 'pp5',  text: 'Episode title includes guest name or topic keyword',   state: 'unchecked' },
      { id: 'pp6',  text: 'Show notes written with key takeaways',               state: 'unchecked' },
      { id: 'pp7',  text: 'Timestamps for chapters included',                    state: 'unchecked' },
      { id: 'pp8',  text: 'Guest bio and links added to show notes',             state: 'unchecked' },
      { id: 'pp9',  text: 'Episode artwork matches brand (3000×3000 PNG)',       state: 'unchecked' },
      { id: 'pp10', text: 'Episode uploaded to hosting platform (Buzzsprout/Transistor)', state: 'unchecked' },
      { id: 'pp11', text: 'Submitted to Spotify, Apple Podcasts, and Google',   state: 'unchecked' },
      { id: 'pp12', text: 'Audiogram or clip created for social promotion',      state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-newsletter-issue',
    name: 'Newsletter Issue',
    description: 'Weekly newsletter writing and publishing checklist for consistent, high-quality issues.',
    category: 'content',
    mode: 'simple',
    tags: ['newsletter', 'writing', 'publishing', 'email'],
    featured: false,
    previewLines: ['Subject line tested with a colleague', 'Opening hook grabs attention in first sentence', 'Links tested in actual email client', 'Sent at consistent day and time'],
    items: [
      { id: 'ni1',  text: 'Topic and angle decided',                              state: 'unchecked' },
      { id: 'ni2',  text: 'Draft written — no editing during first pass',         state: 'unchecked' },
      { id: 'ni3',  text: 'Opening hook grabs attention in first sentence',       state: 'unchecked' },
      { id: 'ni4',  text: 'One clear CTA at the end (not three)',                 state: 'unchecked' },
      { id: 'ni5',  text: 'Edited for clarity — cut every unnecessary sentence',  state: 'unchecked' },
      { id: 'ni6',  text: 'Subject line tested with a colleague',                 state: 'unchecked' },
      { id: 'ni7',  text: 'Preview text set (complements subject line)',          state: 'unchecked' },
      { id: 'ni8',  text: 'All links tested in actual email client',              state: 'unchecked' },
      { id: 'ni9',  text: 'Plain text version reviewed',                          state: 'unchecked' },
      { id: 'ni10', text: 'Unsubscribe link present',                             state: 'unchecked' },
      { id: 'ni11', text: 'Sent at consistent day and time',                      state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-content-repurpose',
    name: 'Content Repurposing',
    description: 'Checklist to systematically repurpose one long-form piece of content across multiple formats.',
    category: 'content',
    mode: 'advanced',
    tags: ['repurposing', 'content strategy', 'social media', 'distribution'],
    featured: false,
    previewLines: ['Source', 'Extract 5 standalone insights from the piece', 'Distribution', 'Thread, carousel, and short-form video created'],
    items: [
      { id: 'cr1',  text: 'Source Content',                                    state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'cr2',  text: 'Core argument or key insight identified',           state: 'unchecked', depth: 1, parentId: 'cr1', collapsed: false },
      { id: 'cr3',  text: '5 standalone insights extracted',                   state: 'unchecked', depth: 1, parentId: 'cr1', collapsed: false },
      { id: 'cr4',  text: 'Best quote or stat highlighted',                    state: 'unchecked', depth: 1, parentId: 'cr1', collapsed: false },
      { id: 'cr5',  text: 'Written Formats',                                   state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'cr6',  text: 'Twitter/X thread drafted (hook + 5 points)',        state: 'unchecked', depth: 1, parentId: 'cr5', collapsed: false },
      { id: 'cr7',  text: 'LinkedIn post adapted for professional tone',       state: 'unchecked', depth: 1, parentId: 'cr5', collapsed: false },
      { id: 'cr8',  text: 'Newsletter section written from core insight',      state: 'unchecked', depth: 1, parentId: 'cr5', collapsed: false },
      { id: 'cr9',  text: 'Visual Formats',                                    state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'cr10', text: 'Instagram/LinkedIn carousel (5–10 slides)',         state: 'unchecked', depth: 1, parentId: 'cr9', collapsed: false },
      { id: 'cr11', text: 'Short-form video script (60–90s) written',         state: 'unchecked', depth: 1, parentId: 'cr9', collapsed: false },
      { id: 'cr12', text: 'Quote graphic created for Stories',                 state: 'unchecked', depth: 1, parentId: 'cr9', collapsed: false },
    ],
  },
]
