import type { ChecklistTemplate } from './types'

export const devopsTemplates: ChecklistTemplate[] = [
  {
    id: 'tpl-incident-response',
    name: 'Incident Response',
    description: 'Step-by-step checklist for handling production incidents from detection to postmortem.',
    category: 'devops',
    mode: 'advanced',
    tags: ['incident', 'on-call', 'production'],
    featured: true,
    previewLines: ['Detect & Triage', 'Confirm incident and severity', 'Mitigate', 'Apply hotfix or rollback'],
    items: [
      { id: 'ir1',  text: 'Detect & Triage',                 state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ir2',  text: 'Confirm incident is real',        state: 'unchecked', depth: 1, parentId: 'ir1', collapsed: false },
      { id: 'ir3',  text: 'Assign severity (P1/P2/P3)',      state: 'unchecked', depth: 1, parentId: 'ir1', collapsed: false },
      { id: 'ir4',  text: 'Page incident commander',         state: 'unchecked', depth: 1, parentId: 'ir1', collapsed: false },
      { id: 'ir5',  text: 'Open incident channel',           state: 'unchecked', depth: 1, parentId: 'ir1', collapsed: false },
      { id: 'ir6',  text: 'Communicate',                     state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ir7',  text: 'Post initial status update',      state: 'unchecked', depth: 1, parentId: 'ir6', collapsed: false },
      { id: 'ir8',  text: 'Notify affected stakeholders',    state: 'unchecked', depth: 1, parentId: 'ir6', collapsed: false },
      { id: 'ir9',  text: 'Mitigate',                        state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ir10', text: 'Identify root cause hypothesis',  state: 'unchecked', depth: 1, parentId: 'ir9', collapsed: false },
      { id: 'ir11', text: 'Apply hotfix or rollback',        state: 'unchecked', depth: 1, parentId: 'ir9', collapsed: false },
      { id: 'ir12', text: 'Verify service restored',         state: 'unchecked', depth: 1, parentId: 'ir9', collapsed: false },
      { id: 'ir13', text: 'Resolve',                         state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ir14', text: 'Post resolution update',          state: 'unchecked', depth: 1, parentId: 'ir13', collapsed: false },
      { id: 'ir15', text: 'Schedule postmortem within 48h',  state: 'unchecked', depth: 1, parentId: 'ir13', collapsed: false },
      { id: 'ir16', text: 'Write postmortem document',       state: 'unchecked', depth: 1, parentId: 'ir13', collapsed: false },
    ],
  },
  {
    id: 'tpl-deployment-runbook',
    name: 'Deployment Runbook',
    description: 'Safe production deployment checklist with pre-checks, execution, and verification steps.',
    category: 'devops',
    mode: 'advanced',
    tags: ['deploy', 'runbook', 'production'],
    featured: false,
    previewLines: ['Pre-Deploy', 'Confirm deploy window agreed', 'Execute', 'Run database migrations'],
    items: [
      { id: 'dr1',  text: 'Pre-Deploy',                       state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'dr2',  text: 'Confirm deploy window agreed',     state: 'unchecked', depth: 1, parentId: 'dr1', collapsed: false },
      { id: 'dr3',  text: 'Verify staging deploy succeeded',  state: 'unchecked', depth: 1, parentId: 'dr1', collapsed: false },
      { id: 'dr4',  text: 'Notify team in #deploys channel',  state: 'unchecked', depth: 1, parentId: 'dr1', collapsed: false },
      { id: 'dr5',  text: 'Confirm rollback procedure ready', state: 'unchecked', depth: 1, parentId: 'dr1', collapsed: false },
      { id: 'dr6',  text: 'Execute',                          state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'dr7',  text: 'Run database migrations',          state: 'unchecked', depth: 1, parentId: 'dr6', collapsed: false },
      { id: 'dr8',  text: 'Verify migration success',         state: 'unchecked', depth: 2, parentId: 'dr7', collapsed: false },
      { id: 'dr9',  text: 'Deploy application version',       state: 'unchecked', depth: 1, parentId: 'dr6', collapsed: false },
      { id: 'dr10', text: 'Update config/feature flags',      state: 'unchecked', depth: 1, parentId: 'dr6', collapsed: false },
      { id: 'dr11', text: 'Verify',                           state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'dr12', text: 'Health checks passing',            state: 'unchecked', depth: 1, parentId: 'dr11', collapsed: false },
      { id: 'dr13', text: 'Key user flows working',           state: 'unchecked', depth: 1, parentId: 'dr11', collapsed: false },
      { id: 'dr14', text: 'Error rate within normal range',   state: 'unchecked', depth: 1, parentId: 'dr11', collapsed: false },
      { id: 'dr15', text: 'Post deploy complete in channel',  state: 'unchecked', depth: 1, parentId: 'dr11', collapsed: false },
    ],
  },
  {
    id: 'tpl-server-hardening',
    name: 'Server Hardening',
    description: 'Security hardening checklist for new Linux servers before going to production.',
    category: 'devops',
    mode: 'simple',
    tags: ['security', 'linux', 'server'],
    featured: false,
    previewLines: ['Disable root SSH login', 'Set up key-based authentication only', 'Configure UFW or iptables firewall', 'Enable automatic security updates'],
    items: [
      { id: 'sh1',  text: 'Disable root SSH login',                    state: 'unchecked' },
      { id: 'sh2',  text: 'Set up key-based authentication only',      state: 'unchecked' },
      { id: 'sh3',  text: 'Disable password authentication in SSH',    state: 'unchecked' },
      { id: 'sh4',  text: 'Change default SSH port',                   state: 'unchecked' },
      { id: 'sh5',  text: 'Configure UFW or iptables firewall',        state: 'unchecked' },
      { id: 'sh6',  text: 'Enable automatic security updates',         state: 'unchecked' },
      { id: 'sh7',  text: 'Install and configure fail2ban',            state: 'unchecked' },
      { id: 'sh8',  text: 'Disable unused services and ports',         state: 'unchecked' },
      { id: 'sh9',  text: 'Set up log monitoring (auditd / CloudWatch)', state: 'unchecked' },
      { id: 'sh10', text: 'Configure NTP time synchronisation',        state: 'unchecked' },
      { id: 'sh11', text: 'Enable disk encryption for sensitive volumes', state: 'unchecked' },
      { id: 'sh12', text: 'Document server in infrastructure register', state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-on-call-handoff',
    name: 'On-Call Handoff',
    description: 'Checklist for handing off on-call responsibilities cleanly between shifts.',
    category: 'devops',
    mode: 'simple',
    tags: ['on-call', 'handoff', 'operations'],
    featured: false,
    previewLines: ['Review open incidents and their status', 'Share any known fragile areas to watch', 'Confirm alerting and paging is active', 'Update runbook with anything new learned'],
    items: [
      { id: 'oc1',  text: 'Review all open incidents and their current status', state: 'unchecked' },
      { id: 'oc2',  text: 'Summarise any ongoing investigations',               state: 'unchecked' },
      { id: 'oc3',  text: 'List known fragile areas or elevated risk today',    state: 'unchecked' },
      { id: 'oc4',  text: 'Confirm alerting and paging routes are active',      state: 'unchecked' },
      { id: 'oc5',  text: 'Verify on-call rotation updated in PagerDuty/Opsgenie', state: 'unchecked' },
      { id: 'oc6',  text: 'Share any pending maintenance windows',              state: 'unchecked' },
      { id: 'oc7',  text: 'Point incoming engineer to recent runbook changes',  state: 'unchecked' },
      { id: 'oc8',  text: 'Note any recent deploys that may need monitoring',   state: 'unchecked' },
      { id: 'oc9',  text: 'Confirm incoming engineer has dashboard access',     state: 'unchecked' },
      { id: 'oc10', text: 'Update runbook with anything new learned this shift', state: 'unchecked' },
    ],
  },
]
