import type { ChecklistTemplate } from './types'

function sid(n: number) { return `e${n}` }

export const engineeringTemplates: ChecklistTemplate[] = [
  {
    id: 'tpl-code-review',
    name: 'Code Review',
    description: 'Structured checklist for reviewing pull requests thoroughly and consistently.',
    category: 'engineering',
    mode: 'simple',
    tags: ['pull request', 'review', 'code quality'],
    featured: true,
    previewLines: ['Read the PR description and linked issue', 'Check for logic errors and edge cases', 'Verify error handling and null checks', 'Review test coverage'],
    items: [
      { id: sid(1),  text: 'Read the PR description and linked issue',         state: 'unchecked' },
      { id: sid(2),  text: 'Understand the intended change before reviewing code', state: 'unchecked' },
      { id: sid(3),  text: 'Check for logic errors and edge cases',             state: 'unchecked' },
      { id: sid(4),  text: 'Verify error handling and null checks',             state: 'unchecked' },
      { id: sid(5),  text: 'Review test coverage — are new paths tested?',      state: 'unchecked' },
      { id: sid(6),  text: 'Check naming: variables, functions, files',         state: 'unchecked' },
      { id: sid(7),  text: 'Look for code duplication that could be extracted', state: 'unchecked' },
      { id: sid(8),  text: 'Verify no secrets or credentials committed',        state: 'unchecked' },
      { id: sid(9),  text: 'Check performance implications for hot paths',      state: 'unchecked' },
      { id: sid(10), text: 'Confirm migration scripts are reversible',           state: 'unchecked' },
      { id: sid(11), text: 'Review API contract changes for backwards compat',  state: 'unchecked' },
      { id: sid(12), text: 'Left a constructive comment or approved',           state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-feature-release',
    name: 'Feature Release',
    description: 'End-to-end checklist for shipping a new feature from staging to production.',
    category: 'engineering',
    mode: 'advanced',
    tags: ['release', 'deploy', 'production'],
    featured: true,
    previewLines: ['Pre-release', 'Staging smoke tests passed', 'Production', 'Enable feature flag'],
    items: [
      { id: 'fr1',  text: 'Pre-release',                    state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'fr2',  text: 'All PRs merged to main',         state: 'unchecked', depth: 1, parentId: 'fr1', collapsed: false },
      { id: 'fr3',  text: 'CI pipeline green',              state: 'unchecked', depth: 1, parentId: 'fr1', collapsed: false },
      { id: 'fr4',  text: 'Staging smoke tests passed',     state: 'unchecked', depth: 1, parentId: 'fr1', collapsed: false },
      { id: 'fr5',  text: 'Rollback plan documented',       state: 'unchecked', depth: 1, parentId: 'fr1', collapsed: false },
      { id: 'fr6',  text: 'Deploy',                         state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'fr7',  text: 'Database migrations run',        state: 'unchecked', depth: 1, parentId: 'fr6', collapsed: false },
      { id: 'fr8',  text: 'Verify migration rollback',      state: 'unchecked', depth: 2, parentId: 'fr7', collapsed: false },
      { id: 'fr9',  text: 'Deploy to production',           state: 'unchecked', depth: 1, parentId: 'fr6', collapsed: false },
      { id: 'fr10', text: 'Enable feature flag',            state: 'unchecked', depth: 1, parentId: 'fr6', collapsed: false },
      { id: 'fr11', text: 'Post-deploy',                    state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'fr12', text: 'Monitor error rates for 15 min', state: 'unchecked', depth: 1, parentId: 'fr11', collapsed: false },
      { id: 'fr13', text: 'Check key metrics dashboards',   state: 'unchecked', depth: 1, parentId: 'fr11', collapsed: false },
      { id: 'fr14', text: 'Notify stakeholders',            state: 'unchecked', depth: 1, parentId: 'fr11', collapsed: false },
      { id: 'fr15', text: 'Update changelog',               state: 'unchecked', depth: 1, parentId: 'fr11', collapsed: false },
    ],
  },
  {
    id: 'tpl-new-project-setup',
    name: 'New Project Setup',
    description: 'Bootstrap checklist for starting a new software project the right way.',
    category: 'engineering',
    mode: 'advanced',
    tags: ['project', 'bootstrap', 'setup'],
    featured: false,
    previewLines: ['Repository', 'Create repo and set branch protection', 'CI/CD', 'Set up lint and test pipeline'],
    items: [
      { id: 'np1',  text: 'Repository',                      state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'np2',  text: 'Create repo and set default branch', state: 'unchecked', depth: 1, parentId: 'np1', collapsed: false },
      { id: 'np3',  text: 'Set branch protection rules',     state: 'unchecked', depth: 1, parentId: 'np1', collapsed: false },
      { id: 'np4',  text: 'Add README with project overview', state: 'unchecked', depth: 1, parentId: 'np1', collapsed: false },
      { id: 'np5',  text: 'Add .gitignore and .editorconfig', state: 'unchecked', depth: 1, parentId: 'np1', collapsed: false },
      { id: 'np6',  text: 'CI/CD',                           state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'np7',  text: 'Set up lint and test pipeline',   state: 'unchecked', depth: 1, parentId: 'np6', collapsed: false },
      { id: 'np8',  text: 'Configure build and deploy pipeline', state: 'unchecked', depth: 1, parentId: 'np6', collapsed: false },
      { id: 'np9',  text: 'Set required environment variables', state: 'unchecked', depth: 1, parentId: 'np6', collapsed: false },
      { id: 'np10', text: 'Security',                        state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'np11', text: 'Enable dependency vulnerability scanning', state: 'unchecked', depth: 1, parentId: 'np10', collapsed: false },
      { id: 'np12', text: 'Add secret scanning to CI',       state: 'unchecked', depth: 1, parentId: 'np10', collapsed: false },
      { id: 'np13', text: 'Document secrets management approach', state: 'unchecked', depth: 1, parentId: 'np10', collapsed: false },
    ],
  },
  {
    id: 'tpl-api-design-review',
    name: 'API Design Review',
    description: 'Checklist for reviewing a REST or GraphQL API design before implementation begins.',
    category: 'engineering',
    mode: 'simple',
    tags: ['api', 'design', 'review', 'rest'],
    featured: false,
    previewLines: ['Resource names are nouns and lowercase', 'Error responses include a code and message', 'Pagination strategy defined', 'Authentication and authorisation documented'],
    items: [
      { id: 'ar1',  text: 'Resource names are nouns, lowercase, plural',     state: 'unchecked' },
      { id: 'ar2',  text: 'HTTP verbs used correctly (GET/POST/PUT/DELETE)',  state: 'unchecked' },
      { id: 'ar3',  text: 'Status codes are appropriate for each response',  state: 'unchecked' },
      { id: 'ar4',  text: 'Error responses include a machine-readable code',  state: 'unchecked' },
      { id: 'ar5',  text: 'Pagination strategy defined (cursor or offset)',   state: 'unchecked' },
      { id: 'ar6',  text: 'Filtering and sorting parameters documented',      state: 'unchecked' },
      { id: 'ar7',  text: 'Authentication and authorisation method clear',    state: 'unchecked' },
      { id: 'ar8',  text: 'Versioning strategy decided (URL path or header)', state: 'unchecked' },
      { id: 'ar9',  text: 'Request and response schemas documented',          state: 'unchecked' },
      { id: 'ar10', text: 'Breaking vs non-breaking changes identified',      state: 'unchecked' },
      { id: 'ar11', text: 'Rate limiting behaviour specified',                state: 'unchecked' },
      { id: 'ar12', text: 'OpenAPI / schema spec updated or created',         state: 'unchecked' },
    ],
  },
]
