import type { ChecklistTemplate } from './types'

export const healthTemplates: ChecklistTemplate[] = [
  {
    id: 'tpl-fitness-week',
    name: 'Weekly Fitness Routine',
    description: 'Simple weekly fitness checklist to build consistent exercise habits and track progress.',
    category: 'health',
    mode: 'simple',
    tags: ['fitness', 'exercise', 'health', 'habit'],
    featured: false,
    previewLines: ['3 strength training sessions completed', 'At least 2 cardio sessions', '8,000+ steps each day tracked', 'Protein target hit daily'],
    items: [
      { id: 'fw1',  text: '3 strength training sessions this week',           state: 'unchecked' },
      { id: 'fw2',  text: '2 cardio sessions (run, cycle, or swim)',          state: 'unchecked' },
      { id: 'fw3',  text: '8,000+ steps per day tracked',                    state: 'unchecked' },
      { id: 'fw4',  text: 'Protein target hit each day (0.8g per lb)',       state: 'unchecked' },
      { id: 'fw5',  text: '7–9 hours sleep per night',                       state: 'unchecked' },
      { id: 'fw6',  text: '2L+ water daily',                                 state: 'unchecked' },
      { id: 'fw7',  text: 'One full rest day with no structured exercise',   state: 'unchecked' },
      { id: 'fw8',  text: 'Note any pain or discomfort to address',          state: 'unchecked' },
      { id: 'fw9',  text: 'Log this week\'s weights or times for progress',  state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-annual-health-review',
    name: 'Annual Health Review',
    description: 'Yearly personal health checklist covering screenings, dental, mental health, and lifestyle habits.',
    category: 'health',
    mode: 'advanced',
    tags: ['health', 'annual review', 'wellness', 'preventive'],
    featured: false,
    previewLines: ['Medical', 'GP check-up booked', 'Mental Health', 'Therapy or peer support reviewed'],
    items: [
      { id: 'ah1',  text: 'Medical',                                         state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ah2',  text: 'Annual GP / primary care check-up booked',       state: 'unchecked', depth: 1, parentId: 'ah1', collapsed: false },
      { id: 'ah3',  text: 'Blood panel (cholesterol, glucose, iron) done',  state: 'unchecked', depth: 1, parentId: 'ah1', collapsed: false },
      { id: 'ah4',  text: 'Dental check-up and clean completed',            state: 'unchecked', depth: 1, parentId: 'ah1', collapsed: false },
      { id: 'ah5',  text: 'Eye test completed',                             state: 'unchecked', depth: 1, parentId: 'ah1', collapsed: false },
      { id: 'ah6',  text: 'Vaccinations up to date (flu, boosters)',        state: 'unchecked', depth: 1, parentId: 'ah1', collapsed: false },
      { id: 'ah7',  text: 'Mental Health',                                  state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ah8',  text: 'Stress level honestly assessed',                 state: 'unchecked', depth: 1, parentId: 'ah7', collapsed: false },
      { id: 'ah9',  text: 'Therapy, coaching, or peer support reviewed',    state: 'unchecked', depth: 1, parentId: 'ah7', collapsed: false },
      { id: 'ah10', text: 'Work-life boundaries evaluated',                 state: 'unchecked', depth: 1, parentId: 'ah7', collapsed: false },
      { id: 'ah11', text: 'Lifestyle',                                      state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ah12', text: 'Average sleep hours reviewed and improved',      state: 'unchecked', depth: 1, parentId: 'ah11', collapsed: false },
      { id: 'ah13', text: 'Alcohol and caffeine habits assessed',           state: 'unchecked', depth: 1, parentId: 'ah11', collapsed: false },
      { id: 'ah14', text: 'One health goal set for the coming year',        state: 'unchecked', depth: 1, parentId: 'ah11', collapsed: false },
    ],
  },
  {
    id: 'tpl-morning-routine',
    name: 'Morning Routine',
    description: 'Intentional morning routine checklist to start each day focused, energised, and clear-headed.',
    category: 'health',
    mode: 'simple',
    tags: ['morning routine', 'habits', 'productivity', 'wellness'],
    featured: false,
    previewLines: ['No phone for first 30 minutes', 'Drink a full glass of water on waking', 'Move — walk, stretch, or exercise', 'Write 3 priorities for the day'],
    items: [
      { id: 'mr1', text: 'No phone for first 30 minutes after waking',        state: 'unchecked' },
      { id: 'mr2', text: 'Drink a full glass of water',                        state: 'unchecked' },
      { id: 'mr3', text: 'Move — walk, stretch, or workout',                  state: 'unchecked' },
      { id: 'mr4', text: 'Shower and get ready intentionally',                state: 'unchecked' },
      { id: 'mr5', text: 'Eat a protein-rich breakfast',                      state: 'unchecked' },
      { id: 'mr6', text: 'Write 3 top priorities for the day',                state: 'unchecked' },
      { id: 'mr7', text: 'Review calendar and flag any conflicts',             state: 'unchecked' },
      { id: 'mr8', text: 'Start with the most important task first',           state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-nutrition-week',
    name: 'Weekly Nutrition Prep',
    description: 'Sunday meal prep checklist to eat well all week without relying on willpower in the moment.',
    category: 'health',
    mode: 'simple',
    tags: ['nutrition', 'meal prep', 'health', 'cooking'],
    featured: false,
    previewLines: ['Meals planned for the week', 'Grocery list written and ingredients bought', 'Proteins batch-cooked for the week', 'Healthy snacks portioned and ready'],
    items: [
      { id: 'mp1',  text: 'Plan meals for each day of the week',              state: 'unchecked' },
      { id: 'mp2',  text: 'Write grocery list from meal plan',                state: 'unchecked' },
      { id: 'mp3',  text: 'Shop — stick to the list',                        state: 'unchecked' },
      { id: 'mp4',  text: 'Batch-cook proteins (chicken, eggs, legumes)',     state: 'unchecked' },
      { id: 'mp5',  text: 'Roast or prep vegetables for easy use',           state: 'unchecked' },
      { id: 'mp6',  text: 'Cook grains or starches in bulk',                 state: 'unchecked' },
      { id: 'mp7',  text: 'Portion snacks into individual servings',         state: 'unchecked' },
      { id: 'mp8',  text: 'Label containers with contents and date',         state: 'unchecked' },
      { id: 'mp9',  text: 'Ensure fridge has visible, easy-grab healthy options', state: 'unchecked' },
    ],
  },
]
