import type { ChecklistTemplate } from './types'

export const marketingTemplates: ChecklistTemplate[] = [
  {
    id: 'tpl-seo-blog-publish',
    name: 'SEO Blog Post Publish',
    description: 'Pre-publish SEO checklist to maximise organic reach for every blog post.',
    category: 'marketing',
    mode: 'simple',
    tags: ['seo', 'blog', 'content', 'publishing'],
    featured: true,
    previewLines: ['Target keyword in title, H1, and first paragraph', 'Meta description under 160 characters', 'Internal links to 2+ relevant posts', 'OG image set for social sharing'],
    items: [
      { id: 'sb1',  text: 'Target keyword researched and confirmed in title',        state: 'unchecked' },
      { id: 'sb2',  text: 'Keyword in H1, first 100 words, and at least one H2',   state: 'unchecked' },
      { id: 'sb3',  text: 'Meta title under 60 characters',                          state: 'unchecked' },
      { id: 'sb4',  text: 'Meta description between 120–160 characters',             state: 'unchecked' },
      { id: 'sb5',  text: 'URL slug is short, lowercase, hyphenated',               state: 'unchecked' },
      { id: 'sb6',  text: 'Images have descriptive alt text',                        state: 'unchecked' },
      { id: 'sb7',  text: 'Internal links to 2+ relevant existing posts',            state: 'unchecked' },
      { id: 'sb8',  text: 'At least 1 external authoritative link',                  state: 'unchecked' },
      { id: 'sb9',  text: 'OG image (1200×630) set for social sharing',             state: 'unchecked' },
      { id: 'sb10', text: 'Canonical URL set correctly',                              state: 'unchecked' },
      { id: 'sb11', text: 'Schema markup added (Article or HowTo)',                  state: 'unchecked' },
      { id: 'sb12', text: 'Post submitted to Google Search Console after publish',   state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-email-campaign',
    name: 'Email Campaign Launch',
    description: 'Checklist to plan, review, and send a marketing email campaign without errors.',
    category: 'marketing',
    mode: 'advanced',
    tags: ['email', 'campaign', 'newsletter', 'marketing'],
    featured: false,
    previewLines: ['Content', 'Subject line A/B tested', 'Pre-Send', 'Unsubscribe link present and working'],
    items: [
      { id: 'ec1',  text: 'Content',                                       state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ec2',  text: 'Subject line tested with 3+ variants',          state: 'unchecked', depth: 1, parentId: 'ec1', collapsed: false },
      { id: 'ec3',  text: 'Preview text complements subject line',         state: 'unchecked', depth: 1, parentId: 'ec1', collapsed: false },
      { id: 'ec4',  text: 'Copy reviewed for typos and tone',              state: 'unchecked', depth: 1, parentId: 'ec1', collapsed: false },
      { id: 'ec5',  text: 'All links tested and tracked with UTM params',  state: 'unchecked', depth: 1, parentId: 'ec1', collapsed: false },
      { id: 'ec6',  text: 'CTA is clear and above the fold',               state: 'unchecked', depth: 1, parentId: 'ec1', collapsed: false },
      { id: 'ec7',  text: 'Pre-Send',                                      state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ec8',  text: 'Test email sent to internal team',              state: 'unchecked', depth: 1, parentId: 'ec7', collapsed: false },
      { id: 'ec9',  text: 'Renders correctly on mobile and desktop',       state: 'unchecked', depth: 1, parentId: 'ec7', collapsed: false },
      { id: 'ec10', text: 'Unsubscribe link present and functional',       state: 'unchecked', depth: 1, parentId: 'ec7', collapsed: false },
      { id: 'ec11', text: 'Sender name and reply-to address correct',      state: 'unchecked', depth: 1, parentId: 'ec7', collapsed: false },
      { id: 'ec12', text: 'Segment / audience list verified',              state: 'unchecked', depth: 1, parentId: 'ec7', collapsed: false },
      { id: 'ec13', text: 'Send time optimised for audience timezone',     state: 'unchecked', depth: 1, parentId: 'ec7', collapsed: false },
      { id: 'ec14', text: 'Post-Send',                                     state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ec15', text: 'Open rate and click rate monitored at 24h',    state: 'unchecked', depth: 1, parentId: 'ec14', collapsed: false },
      { id: 'ec16', text: 'Unsubscribe spike checked',                    state: 'unchecked', depth: 1, parentId: 'ec14', collapsed: false },
      { id: 'ec17', text: 'Conversion goal tracked in analytics',         state: 'unchecked', depth: 1, parentId: 'ec14', collapsed: false },
    ],
  },
  {
    id: 'tpl-social-content-calendar',
    name: 'Social Media Content Week',
    description: 'Weekly social media planning checklist to batch-create and schedule consistent content.',
    category: 'marketing',
    mode: 'simple',
    tags: ['social media', 'content', 'scheduling', 'marketing'],
    featured: false,
    previewLines: ['Review last week\'s top-performing posts', 'Write 5 post drafts for the week', 'Schedule posts for optimal times', 'Engage with comments from previous week'],
    items: [
      { id: 'sc1',  text: 'Review last week\'s analytics — what worked',       state: 'unchecked' },
      { id: 'sc2',  text: 'Pick weekly theme or content pillar',               state: 'unchecked' },
      { id: 'sc3',  text: 'Write 5 post drafts (one per day)',                 state: 'unchecked' },
      { id: 'sc4',  text: 'Create or source visuals for each post',            state: 'unchecked' },
      { id: 'sc5',  text: 'Write captions with hooks in first line',           state: 'unchecked' },
      { id: 'sc6',  text: 'Add relevant hashtags (research, not guesswork)',   state: 'unchecked' },
      { id: 'sc7',  text: 'Schedule posts for optimal audience time slots',    state: 'unchecked' },
      { id: 'sc8',  text: 'Repurpose top post for another platform',           state: 'unchecked' },
      { id: 'sc9',  text: 'Reply to all comments from previous week',          state: 'unchecked' },
      { id: 'sc10', text: 'Engage with 10 accounts in your niche',             state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-landing-page-review',
    name: 'Landing Page Review',
    description: 'Conversion-focused checklist for reviewing a landing page before paid traffic is sent.',
    category: 'marketing',
    mode: 'simple',
    tags: ['landing page', 'cro', 'conversion', 'ads'],
    featured: false,
    previewLines: ['Headline communicates value in under 5 seconds', 'Social proof above the fold', 'CTA button is high contrast and action-oriented', 'Page load time under 3 seconds on mobile'],
    items: [
      { id: 'lp1',  text: 'Headline communicates value in under 5 seconds',       state: 'unchecked' },
      { id: 'lp2',  text: 'Sub-headline answers "who is this for"',               state: 'unchecked' },
      { id: 'lp3',  text: 'Primary CTA is above the fold',                        state: 'unchecked' },
      { id: 'lp4',  text: 'CTA button is high contrast and action-oriented',      state: 'unchecked' },
      { id: 'lp5',  text: 'Social proof (logos, testimonials) above the fold',   state: 'unchecked' },
      { id: 'lp6',  text: 'Key benefit — feature — proof structure in body',      state: 'unchecked' },
      { id: 'lp7',  text: 'FAQ section addresses top objections',                 state: 'unchecked' },
      { id: 'lp8',  text: 'Form has minimal required fields',                     state: 'unchecked' },
      { id: 'lp9',  text: 'Privacy note near form ("no spam")',                   state: 'unchecked' },
      { id: 'lp10', text: 'Mobile layout tested at 375px',                        state: 'unchecked' },
      { id: 'lp11', text: 'Page load under 3s on mobile (LCP < 2.5s)',           state: 'unchecked' },
      { id: 'lp12', text: 'Analytics and conversion pixel firing correctly',      state: 'unchecked' },
    ],
  },
]
