import type { ChecklistTemplate } from './types'

export const operationsTemplates: ChecklistTemplate[] = [
  {
    id: 'tpl-api-release',
    name: 'API Release Checklist',
    description: 'Pre-release checklist for shipping a new public API or breaking API version change.',
    category: 'operations',
    mode: 'advanced',
    tags: ['api', 'release', 'versioning', 'developer'],
    featured: true,
    previewLines: ['Documentation', 'Reference docs published with examples', 'Compatibility', 'Breaking changes listed in changelog'],
    items: [
      { id: 'ar1',  text: 'Documentation',                                    state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ar2',  text: 'Reference docs published with code examples',      state: 'unchecked', depth: 1, parentId: 'ar1', collapsed: false },
      { id: 'ar3',  text: 'Authentication flow documented',                   state: 'unchecked', depth: 1, parentId: 'ar1', collapsed: false },
      { id: 'ar4',  text: 'Error codes documented with remediation steps',   state: 'unchecked', depth: 1, parentId: 'ar1', collapsed: false },
      { id: 'ar5',  text: 'OpenAPI / Swagger spec published',                state: 'unchecked', depth: 1, parentId: 'ar1', collapsed: false },
      { id: 'ar6',  text: 'Compatibility',                                    state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ar7',  text: 'Breaking changes listed in changelog',             state: 'unchecked', depth: 1, parentId: 'ar6', collapsed: false },
      { id: 'ar8',  text: 'Deprecation notices sent to affected consumers',  state: 'unchecked', depth: 1, parentId: 'ar6', collapsed: false },
      { id: 'ar9',  text: 'Versioning strategy applied (v2, date-based)',    state: 'unchecked', depth: 1, parentId: 'ar6', collapsed: false },
      { id: 'ar10', text: 'Operational',                                      state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ar11', text: 'Rate limits documented and enforced',              state: 'unchecked', depth: 1, parentId: 'ar10', collapsed: false },
      { id: 'ar12', text: 'SLA / uptime commitment published',               state: 'unchecked', depth: 1, parentId: 'ar10', collapsed: false },
      { id: 'ar13', text: 'SDK or client library updated',                   state: 'unchecked', depth: 1, parentId: 'ar10', collapsed: false },
      { id: 'ar14', text: 'Changelog and migration guide published',         state: 'unchecked', depth: 1, parentId: 'ar10', collapsed: false },
    ],
  },
  {
    id: 'tpl-daily-standup',
    name: 'Daily Standup',
    description: 'Structured daily standup checklist to keep the team aligned and unblock work fast.',
    category: 'operations',
    mode: 'simple',
    tags: ['standup', 'daily', 'agile', 'team'],
    featured: true,
    previewLines: ['What did I complete yesterday?', 'What am I working on today?', 'Any blockers or dependencies?', 'Action items captured with owners'],
    items: [
      { id: 'ds1', text: 'Each person: what did I complete yesterday?',       state: 'unchecked' },
      { id: 'ds2', text: 'Each person: what am I working on today?',          state: 'unchecked' },
      { id: 'ds3', text: 'Each person: any blockers or dependencies?',        state: 'unchecked' },
      { id: 'ds4', text: 'Blockers assigned an owner to resolve',             state: 'unchecked' },
      { id: 'ds5', text: 'Sprint board updated to reflect current state',     state: 'unchecked' },
      { id: 'ds6', text: 'Any items at risk of missing sprint commitment?',   state: 'unchecked' },
      { id: 'ds7', text: 'Action items written down with owners and due date', state: 'unchecked' },
      { id: 'ds8', text: 'Meeting ended at or under 15 minutes',              state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-vendor-evaluation',
    name: 'Vendor Evaluation',
    description: 'Checklist for evaluating and selecting a third-party vendor or SaaS tool objectively.',
    category: 'operations',
    mode: 'simple',
    tags: ['vendor', 'procurement', 'evaluation', 'saas'],
    featured: false,
    previewLines: ['Requirements list agreed before outreach', 'Pricing and contract terms reviewed by legal', 'Security questionnaire completed', 'Reference customers contacted'],
    items: [
      { id: 've1',  text: 'Internal requirements list agreed and prioritised', state: 'unchecked' },
      { id: 've2',  text: 'Shortlist of 3+ vendors created',                  state: 'unchecked' },
      { id: 've3',  text: 'Product demo attended for each shortlisted vendor', state: 'unchecked' },
      { id: 've4',  text: 'Security questionnaire / SOC 2 report reviewed',   state: 'unchecked' },
      { id: 've5',  text: 'GDPR / data processing agreement reviewed',        state: 'unchecked' },
      { id: 've6',  text: 'Pricing model understood (seats, usage, overage)', state: 'unchecked' },
      { id: 've7',  text: 'Contract terms reviewed by legal',                 state: 'unchecked' },
      { id: 've8',  text: 'Exit / data portability terms understood',         state: 'unchecked' },
      { id: 've9',  text: 'Reference customers contacted and feedback gathered', state: 'unchecked' },
      { id: 've10', text: 'Trial or POC completed before committing',         state: 'unchecked' },
      { id: 've11', text: 'Decision documented and signed off by stakeholders', state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-quarterly-ops-review',
    name: 'Quarterly Ops Review',
    description: 'Quarterly business review checklist to assess operational health across teams and systems.',
    category: 'operations',
    mode: 'advanced',
    tags: ['operations', 'quarterly review', 'qbr', 'team'],
    featured: false,
    previewLines: ['Metrics Review', 'KPIs compared against targets', 'Processes', 'Bottlenecks identified and owned'],
    items: [
      { id: 'qo1',  text: 'Metrics Review',                                   state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'qo2',  text: 'KPIs reviewed against quarterly targets',          state: 'unchecked', depth: 1, parentId: 'qo1', collapsed: false },
      { id: 'qo3',  text: 'Revenue, costs, and margins reviewed',             state: 'unchecked', depth: 1, parentId: 'qo1', collapsed: false },
      { id: 'qo4',  text: 'Customer satisfaction scores reviewed',            state: 'unchecked', depth: 1, parentId: 'qo1', collapsed: false },
      { id: 'qo5',  text: 'Process Review',                                   state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'qo6',  text: 'Bottlenecks and inefficiencies identified',        state: 'unchecked', depth: 1, parentId: 'qo5', collapsed: false },
      { id: 'qo7',  text: 'Automation opportunities listed',                  state: 'unchecked', depth: 1, parentId: 'qo5', collapsed: false },
      { id: 'qo8',  text: 'Tech debt backlog reviewed and prioritised',       state: 'unchecked', depth: 1, parentId: 'qo5', collapsed: false },
      { id: 'qo9',  text: 'Next Quarter',                                     state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'qo10', text: 'OKRs / goals defined for next quarter',           state: 'unchecked', depth: 1, parentId: 'qo9', collapsed: false },
      { id: 'qo11', text: 'Budget and headcount plan approved',               state: 'unchecked', depth: 1, parentId: 'qo9', collapsed: false },
      { id: 'qo12', text: 'Action owners and deadlines assigned',             state: 'unchecked', depth: 1, parentId: 'qo9', collapsed: false },
    ],
  },
]
