import type { ChecklistTemplate } from './types'

export const personalTemplates: ChecklistTemplate[] = [
  {
    id: 'tpl-travel-packing',
    name: 'Travel Packing',
    description: 'Complete packing checklist so you never forget essentials for a trip.',
    category: 'personal',
    mode: 'advanced',
    tags: ['travel', 'packing', 'holiday'],
    featured: false,
    previewLines: ['Documents', 'Passport and travel insurance', 'Tech', 'Laptop and charger', 'Clothing', 'Weather-appropriate outfits'],
    items: [
      { id: 'tp1',  text: 'Documents',                              state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'tp2',  text: 'Passport or national ID',               state: 'unchecked', depth: 1, parentId: 'tp1', collapsed: false },
      { id: 'tp3',  text: 'Travel insurance documents',            state: 'unchecked', depth: 1, parentId: 'tp1', collapsed: false },
      { id: 'tp4',  text: 'Booking confirmations printed/saved',   state: 'unchecked', depth: 1, parentId: 'tp1', collapsed: false },
      { id: 'tp5',  text: 'Tech',                                   state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'tp6',  text: 'Laptop and charger',                    state: 'unchecked', depth: 1, parentId: 'tp5', collapsed: false },
      { id: 'tp7',  text: 'Phone charger and power bank',          state: 'unchecked', depth: 1, parentId: 'tp5', collapsed: false },
      { id: 'tp8',  text: 'Universal adapter if needed',           state: 'unchecked', depth: 1, parentId: 'tp5', collapsed: false },
      { id: 'tp9',  text: 'Earphones or headphones',               state: 'unchecked', depth: 1, parentId: 'tp5', collapsed: false },
      { id: 'tp10', text: 'Clothing',                              state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'tp11', text: 'Weather-appropriate outfits',           state: 'unchecked', depth: 1, parentId: 'tp10', collapsed: false },
      { id: 'tp12', text: 'Smart outfit for dinners/events',       state: 'unchecked', depth: 1, parentId: 'tp10', collapsed: false },
      { id: 'tp13', text: 'Comfortable walking shoes',             state: 'unchecked', depth: 1, parentId: 'tp10', collapsed: false },
      { id: 'tp14', text: 'Toiletries',                            state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'tp15', text: 'Toothbrush and toothpaste',            state: 'unchecked', depth: 1, parentId: 'tp14', collapsed: false },
      { id: 'tp16', text: 'Prescription medications',              state: 'unchecked', depth: 1, parentId: 'tp14', collapsed: false },
      { id: 'tp17', text: 'Sunscreen and lip balm',               state: 'unchecked', depth: 1, parentId: 'tp14', collapsed: false },
    ],
  },
  {
    id: 'tpl-job-search',
    name: 'Job Search',
    description: 'Structured job search checklist to stay organised across applications.',
    category: 'personal',
    mode: 'advanced',
    tags: ['career', 'job search', 'interview'],
    featured: false,
    previewLines: ['Preparation', 'Update resume and LinkedIn', 'For Each Application', 'Tailor resume to role'],
    items: [
      { id: 'js1',  text: 'Preparation',                           state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'js2',  text: 'Update resume and LinkedIn profile',    state: 'unchecked', depth: 1, parentId: 'js1', collapsed: false },
      { id: 'js3',  text: 'Write or update cover letter template', state: 'unchecked', depth: 1, parentId: 'js1', collapsed: false },
      { id: 'js4',  text: 'Define target role and company types',  state: 'unchecked', depth: 1, parentId: 'js1', collapsed: false },
      { id: 'js5',  text: 'Set up job alert notifications',        state: 'unchecked', depth: 1, parentId: 'js1', collapsed: false },
      { id: 'js6',  text: 'For Each Application',                  state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'js7',  text: 'Tailor resume to the role',             state: 'unchecked', depth: 1, parentId: 'js6', collapsed: false },
      { id: 'js8',  text: 'Research company before applying',      state: 'unchecked', depth: 1, parentId: 'js6', collapsed: false },
      { id: 'js9',  text: 'Submit application and track status',   state: 'unchecked', depth: 1, parentId: 'js6', collapsed: false },
      { id: 'js10', text: 'Interview',                             state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'js11', text: 'Prepare answers to common questions',   state: 'unchecked', depth: 1, parentId: 'js10', collapsed: false },
      { id: 'js12', text: 'Prepare 3 questions to ask interviewer', state: 'unchecked', depth: 1, parentId: 'js10', collapsed: false },
      { id: 'js13', text: 'Send thank-you email within 24h',       state: 'unchecked', depth: 1, parentId: 'js10', collapsed: false },
    ],
  },
  {
    id: 'tpl-home-move',
    name: 'Moving House',
    description: 'Complete checklist for moving to a new home without missing anything.',
    category: 'personal',
    mode: 'simple',
    tags: ['moving', 'home', 'admin'],
    featured: false,
    previewLines: ['Notify utilities of change of address', 'Update bank and financial institutions', 'Forward post from old address', 'Book removal company'],
    items: [
      { id: 'hm1',  text: 'Book removal company or hire a van',        state: 'unchecked' },
      { id: 'hm2',  text: 'Start packing non-essentials 4 weeks out',  state: 'unchecked' },
      { id: 'hm3',  text: 'Notify utilities of change of address',     state: 'unchecked' },
      { id: 'hm4',  text: 'Update bank and financial institutions',    state: 'unchecked' },
      { id: 'hm5',  text: 'Forward post from old address',             state: 'unchecked' },
      { id: 'hm6',  text: 'Notify employer and HMRC of new address',   state: 'unchecked' },
      { id: 'hm7',  text: 'Update driving licence and vehicle reg',    state: 'unchecked' },
      { id: 'hm8',  text: 'Register with new GP and dentist',          state: 'unchecked' },
      { id: 'hm9',  text: 'Arrange contents and buildings insurance',  state: 'unchecked' },
      { id: 'hm10', text: 'Take meter readings on move-in day',        state: 'unchecked' },
      { id: 'hm11', text: 'Check all keys and access codes work',      state: 'unchecked' },
      { id: 'hm12', text: 'Test smoke alarms and carbon monoxide detector', state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-freelance-project',
    name: 'Freelance Project',
    description: 'End-to-end checklist for managing a freelance client project from kickoff to invoice.',
    category: 'personal',
    mode: 'advanced',
    tags: ['freelance', 'client', 'project management'],
    featured: false,
    previewLines: ['Kickoff', 'Scope and deliverables agreed in writing', 'During Project', 'Share progress updates on schedule'],
    items: [
      { id: 'fp1',  text: 'Kickoff',                                       state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'fp2',  text: 'Scope and deliverables agreed in writing',      state: 'unchecked', depth: 1, parentId: 'fp1', collapsed: false },
      { id: 'fp3',  text: 'Contract signed by both parties',               state: 'unchecked', depth: 1, parentId: 'fp1', collapsed: false },
      { id: 'fp4',  text: 'Deposit or first payment received',             state: 'unchecked', depth: 1, parentId: 'fp1', collapsed: false },
      { id: 'fp5',  text: 'Access and assets received from client',        state: 'unchecked', depth: 1, parentId: 'fp1', collapsed: false },
      { id: 'fp6',  text: 'During Project',                                state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'fp7',  text: 'Share progress update at agreed checkpoints',   state: 'unchecked', depth: 1, parentId: 'fp6', collapsed: false },
      { id: 'fp8',  text: 'Log hours or work completed',                   state: 'unchecked', depth: 1, parentId: 'fp6', collapsed: false },
      { id: 'fp9',  text: 'Get written approval for scope changes',        state: 'unchecked', depth: 1, parentId: 'fp6', collapsed: false },
      { id: 'fp10', text: 'Wrap Up',                                        state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'fp11', text: 'Deliver final files in agreed formats',         state: 'unchecked', depth: 1, parentId: 'fp10', collapsed: false },
      { id: 'fp12', text: 'Client signs off on final delivery',            state: 'unchecked', depth: 1, parentId: 'fp10', collapsed: false },
      { id: 'fp13', text: 'Send final invoice',                            state: 'unchecked', depth: 1, parentId: 'fp10', collapsed: false },
      { id: 'fp14', text: 'Request a testimonial or referral',             state: 'unchecked', depth: 1, parentId: 'fp10', collapsed: false },
    ],
  },
]
