import type { ChecklistTemplate } from './types'

export const planningTemplates: ChecklistTemplate[] = [
  {
    id: 'tpl-sprint-planning',
    name: 'Sprint Planning',
    description: 'Checklist to run an effective agile sprint planning meeting.',
    category: 'planning',
    mode: 'simple',
    tags: ['agile', 'scrum', 'sprint', 'meeting'],
    featured: false,
    previewLines: ['Review and close previous sprint', 'Check team capacity for this sprint', 'Walk through backlog top items', 'Agree on sprint goal'],
    items: [
      { id: 'sp1',  text: 'Review and close previous sprint',           state: 'unchecked' },
      { id: 'sp2',  text: 'Check team capacity for this sprint',        state: 'unchecked' },
      { id: 'sp3',  text: 'Walk through backlog top items',             state: 'unchecked' },
      { id: 'sp4',  text: 'Confirm acceptance criteria are clear',      state: 'unchecked' },
      { id: 'sp5',  text: 'Estimate effort for each item',              state: 'unchecked' },
      { id: 'sp6',  text: 'Agree on sprint goal',                       state: 'unchecked' },
      { id: 'sp7',  text: 'Assign items to team members',               state: 'unchecked' },
      { id: 'sp8',  text: 'Identify dependencies and blockers upfront', state: 'unchecked' },
      { id: 'sp9',  text: 'Update sprint board',                        state: 'unchecked' },
      { id: 'sp10', text: 'Confirm sprint dates and next ceremonies',   state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-product-launch',
    name: 'Product Launch',
    description: 'Full product launch checklist covering product, marketing, and customer success.',
    category: 'planning',
    mode: 'advanced',
    tags: ['launch', 'go-to-market', 'product'],
    featured: true,
    previewLines: ['Product', 'Feature complete and QA signed off', 'Marketing', 'Announce blog post ready'],
    items: [
      { id: 'pl1',  text: 'Product',                                   state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'pl2',  text: 'Feature complete and QA signed off',        state: 'unchecked', depth: 1, parentId: 'pl1', collapsed: false },
      { id: 'pl3',  text: 'Documentation published',                   state: 'unchecked', depth: 1, parentId: 'pl1', collapsed: false },
      { id: 'pl4',  text: 'Analytics events instrumented',             state: 'unchecked', depth: 1, parentId: 'pl1', collapsed: false },
      { id: 'pl5',  text: 'Support team briefed',                      state: 'unchecked', depth: 1, parentId: 'pl1', collapsed: false },
      { id: 'pl6',  text: 'Marketing',                                 state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'pl7',  text: 'Announcement blog post ready',              state: 'unchecked', depth: 1, parentId: 'pl6', collapsed: false },
      { id: 'pl8',  text: 'Social media posts scheduled',              state: 'unchecked', depth: 1, parentId: 'pl6', collapsed: false },
      { id: 'pl9',  text: 'Email campaign sent to list',               state: 'unchecked', depth: 1, parentId: 'pl6', collapsed: false },
      { id: 'pl10', text: 'Press release distributed',                 state: 'unchecked', depth: 1, parentId: 'pl6', collapsed: false },
      { id: 'pl11', text: 'Post-Launch',                               state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'pl12', text: 'Monitor user feedback channels',            state: 'unchecked', depth: 1, parentId: 'pl11', collapsed: false },
      { id: 'pl13', text: 'Review key metrics at 24h and 7 days',      state: 'unchecked', depth: 1, parentId: 'pl11', collapsed: false },
      { id: 'pl14', text: 'Team retrospective on launch process',      state: 'unchecked', depth: 1, parentId: 'pl11', collapsed: false },
    ],
  },
  {
    id: 'tpl-technical-spec',
    name: 'Technical Spec Review',
    description: 'Checklist for reviewing and approving a technical design document.',
    category: 'planning',
    mode: 'simple',
    tags: ['design doc', 'architecture', 'review'],
    featured: false,
    previewLines: ['Problem statement is clear and scoped', 'Alternatives considered and documented', 'Data model changes identified', 'Security implications reviewed'],
    items: [
      { id: 'ts1',  text: 'Problem statement is clear and scoped',      state: 'unchecked' },
      { id: 'ts2',  text: 'Success criteria defined and measurable',     state: 'unchecked' },
      { id: 'ts3',  text: 'Alternatives considered and documented',      state: 'unchecked' },
      { id: 'ts4',  text: 'Data model changes identified',               state: 'unchecked' },
      { id: 'ts5',  text: 'API contracts defined',                       state: 'unchecked' },
      { id: 'ts6',  text: 'Security implications reviewed',              state: 'unchecked' },
      { id: 'ts7',  text: 'Performance and scalability addressed',       state: 'unchecked' },
      { id: 'ts8',  text: 'Rollout and migration plan clear',            state: 'unchecked' },
      { id: 'ts9',  text: 'Risks and open questions listed',             state: 'unchecked' },
      { id: 'ts10', text: 'Approvals collected from stakeholders',       state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-retrospective',
    name: 'Sprint Retrospective',
    description: 'Structured retrospective checklist to surface wins, blockers, and actionable improvements.',
    category: 'planning',
    mode: 'advanced',
    tags: ['agile', 'retrospective', 'scrum', 'team'],
    featured: false,
    previewLines: ['Set the Stage', 'Confirm safe-to-speak environment', 'What Went Well', 'Highlight team wins and good practices'],
    items: [
      { id: 'rv1',  text: 'Set the Stage',                                state: 'unchecked', depth: 0, parentId: null,   collapsed: false },
      { id: 'rv2',  text: 'Confirm safe-to-speak environment',            state: 'unchecked', depth: 1, parentId: 'rv1',  collapsed: false },
      { id: 'rv3',  text: 'Review sprint goal and outcome',               state: 'unchecked', depth: 1, parentId: 'rv1',  collapsed: false },
      { id: 'rv4',  text: 'What Went Well',                               state: 'unchecked', depth: 0, parentId: null,   collapsed: false },
      { id: 'rv5',  text: 'Each person shares one win',                   state: 'unchecked', depth: 1, parentId: 'rv4',  collapsed: false },
      { id: 'rv6',  text: 'Highlight team practices to continue',         state: 'unchecked', depth: 1, parentId: 'rv4',  collapsed: false },
      { id: 'rv7',  text: 'What Could Improve',                           state: 'unchecked', depth: 0, parentId: null,   collapsed: false },
      { id: 'rv8',  text: 'Gather pain points anonymously if needed',     state: 'unchecked', depth: 1, parentId: 'rv7',  collapsed: false },
      { id: 'rv9',  text: 'Group themes and vote on top issues',          state: 'unchecked', depth: 1, parentId: 'rv7',  collapsed: false },
      { id: 'rv10', text: 'Action Items',                                  state: 'unchecked', depth: 0, parentId: null,   collapsed: false },
      { id: 'rv11', text: 'Define 1-3 concrete actions with owners',      state: 'unchecked', depth: 1, parentId: 'rv10', collapsed: false },
      { id: 'rv12', text: 'Review actions from previous retro',           state: 'unchecked', depth: 1, parentId: 'rv10', collapsed: false },
      { id: 'rv13', text: 'Add action items to next sprint backlog',      state: 'unchecked', depth: 1, parentId: 'rv10', collapsed: false },
    ],
  },
]
