import type { ChecklistTemplate } from './types'

export const productivityTemplates: ChecklistTemplate[] = [
  {
    id: 'tpl-weekly-review',
    name: 'Weekly Review',
    description: 'GTD-inspired weekly review to clear your head and plan the week ahead.',
    category: 'productivity',
    mode: 'simple',
    tags: ['gtd', 'weekly review', 'planning'],
    featured: true,
    previewLines: ['Clear email inbox to zero', 'Review notes and captures from the week', 'Update project statuses', 'Plan top 3 priorities for next week'],
    items: [
      { id: 'wr1',  text: 'Clear email inbox to zero',                  state: 'unchecked' },
      { id: 'wr2',  text: 'Process all notes and captures from the week', state: 'unchecked' },
      { id: 'wr3',  text: 'Review each active project status',          state: 'unchecked' },
      { id: 'wr4',  text: 'Identify any stalled or blocked items',      state: 'unchecked' },
      { id: 'wr5',  text: 'Review calendar for next week',              state: 'unchecked' },
      { id: 'wr6',  text: 'Plan top 3 priorities for next week',        state: 'unchecked' },
      { id: 'wr7',  text: 'Clear browser tabs and bookmarks',           state: 'unchecked' },
      { id: 'wr8',  text: 'Review financial or admin tasks pending',    state: 'unchecked' },
      { id: 'wr9',  text: 'Write one sentence reflection on the week',  state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-meeting-prep',
    name: 'Meeting Preparation',
    description: 'Checklist to prepare for and follow up on important meetings.',
    category: 'productivity',
    mode: 'advanced',
    tags: ['meeting', 'preparation', 'follow-up'],
    featured: false,
    previewLines: ['Before Meeting', 'Define the meeting objective', 'During Meeting', 'Capture action items'],
    items: [
      { id: 'mp1',  text: 'Before Meeting',                        state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'mp2',  text: 'Define the meeting objective',          state: 'unchecked', depth: 1, parentId: 'mp1', collapsed: false },
      { id: 'mp3',  text: 'Prepare agenda and share in advance',   state: 'unchecked', depth: 1, parentId: 'mp1', collapsed: false },
      { id: 'mp4',  text: 'Review any pre-reads or context docs',  state: 'unchecked', depth: 1, parentId: 'mp1', collapsed: false },
      { id: 'mp5',  text: 'Confirm attendees and calendar link',   state: 'unchecked', depth: 1, parentId: 'mp1', collapsed: false },
      { id: 'mp6',  text: 'During Meeting',                        state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'mp7',  text: 'Capture action items with owners',      state: 'unchecked', depth: 1, parentId: 'mp6', collapsed: false },
      { id: 'mp8',  text: 'Note key decisions made',               state: 'unchecked', depth: 1, parentId: 'mp6', collapsed: false },
      { id: 'mp9',  text: 'After Meeting',                         state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'mp10', text: 'Send meeting notes and action items',   state: 'unchecked', depth: 1, parentId: 'mp9', collapsed: false },
      { id: 'mp11', text: 'Add action items to your task system',  state: 'unchecked', depth: 1, parentId: 'mp9', collapsed: false },
      { id: 'mp12', text: 'Schedule follow-up if needed',          state: 'unchecked', depth: 1, parentId: 'mp9', collapsed: false },
    ],
  },
  {
    id: 'tpl-onboarding',
    name: 'New Employee Onboarding',
    description: 'First-week onboarding checklist to get a new team member up to speed.',
    category: 'productivity',
    mode: 'advanced',
    tags: ['onboarding', 'hiring', 'hr'],
    featured: false,
    previewLines: ['Day 1', 'Account access provisioned', 'Week 1', 'Meet with manager 1:1'],
    items: [
      { id: 'ob1',  text: 'Day 1',                                    state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ob2',  text: 'Account access provisioned',               state: 'unchecked', depth: 1, parentId: 'ob1', collapsed: false },
      { id: 'ob3',  text: 'Dev environment set up',                   state: 'unchecked', depth: 1, parentId: 'ob1', collapsed: false },
      { id: 'ob4',  text: 'Team introductions done',                  state: 'unchecked', depth: 1, parentId: 'ob1', collapsed: false },
      { id: 'ob5',  text: 'HR paperwork completed',                   state: 'unchecked', depth: 1, parentId: 'ob1', collapsed: false },
      { id: 'ob6',  text: 'Week 1',                                   state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ob7',  text: 'Meet with manager 1:1',                    state: 'unchecked', depth: 1, parentId: 'ob6', collapsed: false },
      { id: 'ob8',  text: 'Read engineering/team handbook',           state: 'unchecked', depth: 1, parentId: 'ob6', collapsed: false },
      { id: 'ob9',  text: 'Complete first small task or PR',          state: 'unchecked', depth: 1, parentId: 'ob6', collapsed: false },
      { id: 'ob10', text: 'Shadow a customer support session',        state: 'unchecked', depth: 1, parentId: 'ob6', collapsed: false },
      { id: 'ob11', text: 'Month 1',                                  state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ob12', text: '30-day check-in with manager',             state: 'unchecked', depth: 1, parentId: 'ob11', collapsed: false },
      { id: 'ob13', text: 'Completed first solo project or feature',  state: 'unchecked', depth: 1, parentId: 'ob11', collapsed: false },
    ],
  },
  {
    id: 'tpl-deep-work',
    name: 'Deep Work Session',
    description: 'Pre-session setup and post-session wind-down checklist for distraction-free focused work.',
    category: 'productivity',
    mode: 'simple',
    tags: ['focus', 'deep work', 'productivity'],
    featured: false,
    previewLines: ['Write down the one goal for this session', 'Close Slack, email, and social media', 'Set a timer for 90 minutes', 'Capture anything left unfinished'],
    items: [
      { id: 'dw1',  text: 'Write down the one goal for this session',       state: 'unchecked' },
      { id: 'dw2',  text: 'Close Slack, email, and social media tabs',      state: 'unchecked' },
      { id: 'dw3',  text: 'Put phone on Do Not Disturb',                    state: 'unchecked' },
      { id: 'dw4',  text: 'Get water and anything else you need nearby',    state: 'unchecked' },
      { id: 'dw5',  text: 'Set a timer (90 min recommended)',                state: 'unchecked' },
      { id: 'dw6',  text: 'Start work — honour the session boundary',       state: 'unchecked' },
      { id: 'dw7',  text: 'Take a short break when timer ends',             state: 'unchecked' },
      { id: 'dw8',  text: 'Capture anything left unfinished in your task list', state: 'unchecked' },
      { id: 'dw9',  text: 'Note one thing you accomplished this session',   state: 'unchecked' },
    ],
  },
]
