import type { ChecklistTemplate } from './types'

export const qaTemplates: ChecklistTemplate[] = [
  {
    id: 'tpl-api-testing',
    name: 'API Testing',
    description: 'Checklist for testing REST APIs thoroughly before release.',
    category: 'qa',
    mode: 'advanced',
    tags: ['api', 'rest', 'testing'],
    featured: false,
    previewLines: ['Functional Tests', 'Happy path returns 200 with correct body', 'Security', 'Unauthenticated requests return 401'],
    items: [
      { id: 'at1',  text: 'Functional Tests',                         state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'at2',  text: 'Happy path returns 200 with correct body', state: 'unchecked', depth: 1, parentId: 'at1', collapsed: false },
      { id: 'at3',  text: 'Invalid inputs return 400 with message',   state: 'unchecked', depth: 1, parentId: 'at1', collapsed: false },
      { id: 'at4',  text: 'Missing required fields handled',          state: 'unchecked', depth: 1, parentId: 'at1', collapsed: false },
      { id: 'at5',  text: 'Pagination works correctly',               state: 'unchecked', depth: 1, parentId: 'at1', collapsed: false },
      { id: 'at6',  text: 'Security',                                 state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'at7',  text: 'Unauthenticated requests return 401',      state: 'unchecked', depth: 1, parentId: 'at6', collapsed: false },
      { id: 'at8',  text: 'Unauthorized roles return 403',            state: 'unchecked', depth: 1, parentId: 'at6', collapsed: false },
      { id: 'at9',  text: 'SQL injection inputs handled safely',       state: 'unchecked', depth: 1, parentId: 'at6', collapsed: false },
      { id: 'at10', text: 'Rate limiting enforced',                   state: 'unchecked', depth: 1, parentId: 'at6', collapsed: false },
      { id: 'at11', text: 'Performance',                              state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'at12', text: 'P95 latency within SLA under normal load', state: 'unchecked', depth: 1, parentId: 'at11', collapsed: false },
      { id: 'at13', text: 'Behaviour under high concurrency tested',  state: 'unchecked', depth: 1, parentId: 'at11', collapsed: false },
    ],
  },
  {
    id: 'tpl-regression-testing',
    name: 'Regression Testing',
    description: 'Pre-release regression checklist to verify core flows are not broken.',
    category: 'qa',
    mode: 'simple',
    tags: ['regression', 'pre-release', 'testing'],
    featured: false,
    previewLines: ['User login and logout flows', 'Core CRUD operations', 'Payment or checkout flow', 'Email notifications triggered'],
    items: [
      { id: 'rt1',  text: 'User login and logout flows',              state: 'unchecked' },
      { id: 'rt2',  text: 'Sign-up and email verification',           state: 'unchecked' },
      { id: 'rt3',  text: 'Password reset flow',                      state: 'unchecked' },
      { id: 'rt4',  text: 'Core CRUD operations',                     state: 'unchecked' },
      { id: 'rt5',  text: 'Search and filter functionality',          state: 'unchecked' },
      { id: 'rt6',  text: 'Payment or checkout flow',                 state: 'unchecked' },
      { id: 'rt7',  text: 'Email notifications triggered',            state: 'unchecked' },
      { id: 'rt8',  text: 'File upload and download',                 state: 'unchecked' },
      { id: 'rt9',  text: 'Responsive layout at 375px and 1440px',    state: 'unchecked' },
      { id: 'rt10', text: 'Dark mode visual check',                   state: 'unchecked' },
      { id: 'rt11', text: 'Keyboard navigation through main flows',   state: 'unchecked' },
      { id: 'rt12', text: 'No console errors in browser DevTools',    state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-accessibility-audit',
    name: 'Accessibility Audit',
    description: 'Practical accessibility checklist for auditing web pages against WCAG 2.1.',
    category: 'qa',
    mode: 'advanced',
    tags: ['accessibility', 'a11y', 'wcag'],
    featured: false,
    previewLines: ['Keyboard & Focus', 'All interactive elements keyboard reachable', 'Screen Reader', 'Images have meaningful alt text'],
    items: [
      { id: 'aa1',  text: 'Keyboard & Focus',                          state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'aa2',  text: 'All interactive elements keyboard reachable', state: 'unchecked', depth: 1, parentId: 'aa1', collapsed: false },
      { id: 'aa3',  text: 'Focus indicator always visible',            state: 'unchecked', depth: 1, parentId: 'aa1', collapsed: false },
      { id: 'aa4',  text: 'Tab order is logical',                      state: 'unchecked', depth: 1, parentId: 'aa1', collapsed: false },
      { id: 'aa5',  text: 'No keyboard traps',                         state: 'unchecked', depth: 1, parentId: 'aa1', collapsed: false },
      { id: 'aa6',  text: 'Screen Reader',                             state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'aa7',  text: 'Images have meaningful alt text',           state: 'unchecked', depth: 1, parentId: 'aa6', collapsed: false },
      { id: 'aa8',  text: 'Form inputs have associated labels',        state: 'unchecked', depth: 1, parentId: 'aa6', collapsed: false },
      { id: 'aa9',  text: 'Page has a unique title',                   state: 'unchecked', depth: 1, parentId: 'aa6', collapsed: false },
      { id: 'aa10', text: 'Headings form a logical hierarchy',         state: 'unchecked', depth: 1, parentId: 'aa6', collapsed: false },
      { id: 'aa11', text: 'Colour & Contrast',                         state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'aa12', text: 'Text contrast ratio ≥ 4.5:1 (AA)',          state: 'unchecked', depth: 1, parentId: 'aa11', collapsed: false },
      { id: 'aa13', text: 'No colour alone conveys meaning',           state: 'unchecked', depth: 1, parentId: 'aa11', collapsed: false },
    ],
  },
  {
    id: 'tpl-security-review',
    name: 'Security Review',
    description: 'Pre-release security checklist covering OWASP top 10 and common web vulnerabilities.',
    category: 'qa',
    mode: 'simple',
    tags: ['security', 'owasp', 'penetration testing'],
    featured: true,
    previewLines: ['Validate and sanitise all user inputs', 'Verify no sensitive data in logs or responses', 'Check for insecure direct object references', 'Confirm HTTPS enforced everywhere'],
    items: [
      { id: 'sr1',  text: 'Validate and sanitise all user inputs',           state: 'unchecked' },
      { id: 'sr2',  text: 'Check for SQL injection in all query paths',      state: 'unchecked' },
      { id: 'sr3',  text: 'Verify XSS protections in place (CSP headers)',   state: 'unchecked' },
      { id: 'sr4',  text: 'Confirm HTTPS enforced and HSTS header set',      state: 'unchecked' },
      { id: 'sr5',  text: 'Check for insecure direct object references',     state: 'unchecked' },
      { id: 'sr6',  text: 'Verify authentication tokens expire correctly',    state: 'unchecked' },
      { id: 'sr7',  text: 'No sensitive data in URLs, logs, or error responses', state: 'unchecked' },
      { id: 'sr8',  text: 'CSRF protections on all state-changing endpoints', state: 'unchecked' },
      { id: 'sr9',  text: 'Dependency audit run — no high severity CVEs',    state: 'unchecked' },
      { id: 'sr10', text: 'Secrets not hardcoded in source or build output', state: 'unchecked' },
      { id: 'sr11', text: 'File uploads restricted to allowed types and size', state: 'unchecked' },
      { id: 'sr12', text: 'Security headers present (X-Frame-Options, etc)', state: 'unchecked' },
    ],
  },
]
