import type { ChecklistTemplate } from './types'

export const remoteTemplates: ChecklistTemplate[] = [
  {
    id: 'tpl-remote-team-setup',
    name: 'Remote Team Setup',
    description: 'Checklist to set up async-first remote work practices for a new or growing distributed team.',
    category: 'remote',
    mode: 'advanced',
    tags: ['remote work', 'async', 'distributed team', 'tools'],
    featured: true,
    previewLines: ['Communication', 'Async-first norms documented', 'Tooling', 'Single source of truth for docs defined'],
    items: [
      { id: 'rt1',  text: 'Communication',                                    state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'rt2',  text: 'Async-first communication norms written down',     state: 'unchecked', depth: 1, parentId: 'rt1', collapsed: false },
      { id: 'rt3',  text: 'Core hours overlap window agreed across timezones', state: 'unchecked', depth: 1, parentId: 'rt1', collapsed: false },
      { id: 'rt4',  text: 'Response time expectations set per channel',       state: 'unchecked', depth: 1, parentId: 'rt1', collapsed: false },
      { id: 'rt5',  text: 'Video call etiquette guide shared',                state: 'unchecked', depth: 1, parentId: 'rt1', collapsed: false },
      { id: 'rt6',  text: 'Tooling',                                          state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'rt7',  text: 'Single source of truth for docs agreed (Notion/Confluence)', state: 'unchecked', depth: 1, parentId: 'rt6', collapsed: false },
      { id: 'rt8',  text: 'Project management tool and workflow set up',      state: 'unchecked', depth: 1, parentId: 'rt6', collapsed: false },
      { id: 'rt9',  text: 'Video call platform decided with backup',          state: 'unchecked', depth: 1, parentId: 'rt6', collapsed: false },
      { id: 'rt10', text: 'Culture',                                          state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'rt11', text: 'Team social rituals scheduled (weekly coffee chat)', state: 'unchecked', depth: 1, parentId: 'rt10', collapsed: false },
      { id: 'rt12', text: 'Recognition system for async contributions',       state: 'unchecked', depth: 1, parentId: 'rt10', collapsed: false },
      { id: 'rt13', text: 'Handbook or team readme for new joiners',          state: 'unchecked', depth: 1, parentId: 'rt10', collapsed: false },
    ],
  },
  {
    id: 'tpl-home-office-setup',
    name: 'Home Office Setup',
    description: 'Practical checklist for setting up a productive, ergonomic, and professional home office.',
    category: 'remote',
    mode: 'simple',
    tags: ['home office', 'ergonomics', 'remote work', 'setup'],
    featured: false,
    previewLines: ['Monitor at eye level to prevent neck strain', 'Dedicated work area separate from relaxation space', 'Reliable internet with wired backup option', 'Good lighting that doesn\'t cause glare on screen'],
    items: [
      { id: 'ho1',  text: 'Dedicated desk or workspace separate from relaxation area', state: 'unchecked' },
      { id: 'ho2',  text: 'Monitor at eye level (top third of screen at eye height)',  state: 'unchecked' },
      { id: 'ho3',  text: 'Chair supports lumbar and feet flat on floor',              state: 'unchecked' },
      { id: 'ho4',  text: 'Reliable internet with speed ≥ 25 Mbps upload',           state: 'unchecked' },
      { id: 'ho5',  text: 'Wired ethernet option available for calls',               state: 'unchecked' },
      { id: 'ho6',  text: 'Good lighting — no screen glare, face lit for calls',    state: 'unchecked' },
      { id: 'ho7',  text: 'External keyboard and mouse (not laptop keyboard)',        state: 'unchecked' },
      { id: 'ho8',  text: 'Quality headset with noise cancellation',                 state: 'unchecked' },
      { id: 'ho9',  text: 'Neutral, clutter-free background for video calls',        state: 'unchecked' },
      { id: 'ho10', text: 'UPS or surge protector for equipment',                    state: 'unchecked' },
      { id: 'ho11', text: 'Work hours and boundaries communicated to household',      state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-async-standup',
    name: 'Async Standup Template',
    description: 'Daily async standup checklist for remote teams to stay aligned without synchronous meetings.',
    category: 'remote',
    mode: 'simple',
    tags: ['async', 'standup', 'remote', 'daily'],
    featured: false,
    previewLines: ['Yesterday\'s completed tasks posted', 'Today\'s top 3 priorities shared', 'Blockers flagged with needed help', 'Availability windows for the day noted'],
    items: [
      { id: 'as1', text: 'Post yesterday\'s completed tasks in standup channel',  state: 'unchecked' },
      { id: 'as2', text: 'Share today\'s top 3 priorities',                       state: 'unchecked' },
      { id: 'as3', text: 'Flag any blockers with what help is needed',            state: 'unchecked' },
      { id: 'as4', text: 'Note availability windows and timezone for the day',    state: 'unchecked' },
      { id: 'as5', text: 'React or acknowledge teammates\' updates',              state: 'unchecked' },
      { id: 'as6', text: 'Review any PRs or tasks assigned to you',              state: 'unchecked' },
      { id: 'as7', text: 'Update task board with current status',                state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-remote-offsite',
    name: 'Remote Team Offsite',
    description: 'Planning checklist for organising a productive in-person offsite for a remote team.',
    category: 'remote',
    mode: 'advanced',
    tags: ['offsite', 'remote team', 'team building', 'planning'],
    featured: false,
    previewLines: ['Logistics', 'Travel and accommodation booked', 'Agenda', 'Balance of work sessions and social time'],
    items: [
      { id: 'ro1',  text: 'Logistics',                                       state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ro2',  text: 'Dates agreed 6–8 weeks in advance',              state: 'unchecked', depth: 1, parentId: 'ro1', collapsed: false },
      { id: 'ro3',  text: 'Location accessible for all team members',       state: 'unchecked', depth: 1, parentId: 'ro1', collapsed: false },
      { id: 'ro4',  text: 'Travel and accommodation booked',                state: 'unchecked', depth: 1, parentId: 'ro1', collapsed: false },
      { id: 'ro5',  text: 'Dietary requirements collected',                 state: 'unchecked', depth: 1, parentId: 'ro1', collapsed: false },
      { id: 'ro6',  text: 'Agenda',                                         state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ro7',  text: 'Clear objectives for offsite defined upfront',   state: 'unchecked', depth: 1, parentId: 'ro6', collapsed: false },
      { id: 'ro8',  text: 'Balance of strategy sessions and social time',   state: 'unchecked', depth: 1, parentId: 'ro6', collapsed: false },
      { id: 'ro9',  text: 'Sessions facilitated not just presented',        state: 'unchecked', depth: 1, parentId: 'ro6', collapsed: false },
      { id: 'ro10', text: 'Post-Offsite',                                   state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ro11', text: 'Key decisions and action items documented',      state: 'unchecked', depth: 1, parentId: 'ro10', collapsed: false },
      { id: 'ro12', text: 'Async summary shared with the team',             state: 'unchecked', depth: 1, parentId: 'ro10', collapsed: false },
    ],
  },
]
