import type { ChecklistTemplate } from './types'

export const securityTemplates: ChecklistTemplate[] = [
  {
    id: 'tpl-security-audit',
    name: 'Security Audit',
    description: 'Comprehensive security audit checklist for web applications covering OWASP, infrastructure, and access controls.',
    category: 'security',
    mode: 'advanced',
    tags: ['security', 'audit', 'owasp', 'compliance'],
    featured: true,
    previewLines: ['Application Security', 'Input validation on all endpoints', 'Infrastructure', 'No public S3 buckets or storage'],
    items: [
      { id: 'sa1',  text: 'Application Security',                          state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'sa2',  text: 'Input validation on all user-facing endpoints', state: 'unchecked', depth: 1, parentId: 'sa1', collapsed: false },
      { id: 'sa3',  text: 'SQL injection — parameterised queries used',    state: 'unchecked', depth: 1, parentId: 'sa1', collapsed: false },
      { id: 'sa4',  text: 'XSS — output escaped, CSP header set',         state: 'unchecked', depth: 1, parentId: 'sa1', collapsed: false },
      { id: 'sa5',  text: 'CSRF tokens on all state-changing requests',   state: 'unchecked', depth: 1, parentId: 'sa1', collapsed: false },
      { id: 'sa6',  text: 'Auth & Access',                                 state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'sa7',  text: 'Passwords hashed with bcrypt/argon2',          state: 'unchecked', depth: 1, parentId: 'sa6', collapsed: false },
      { id: 'sa8',  text: 'Session tokens expire and rotate after login', state: 'unchecked', depth: 1, parentId: 'sa6', collapsed: false },
      { id: 'sa9',  text: 'Least-privilege roles enforced',               state: 'unchecked', depth: 1, parentId: 'sa6', collapsed: false },
      { id: 'sa10', text: 'MFA available for admin accounts',             state: 'unchecked', depth: 1, parentId: 'sa6', collapsed: false },
      { id: 'sa11', text: 'Infrastructure',                               state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'sa12', text: 'No public S3 buckets or blob storage',        state: 'unchecked', depth: 1, parentId: 'sa11', collapsed: false },
      { id: 'sa13', text: 'Secrets in env vars, not source code',        state: 'unchecked', depth: 1, parentId: 'sa11', collapsed: false },
      { id: 'sa14', text: 'TLS 1.2+ enforced, HSTS header set',          state: 'unchecked', depth: 1, parentId: 'sa11', collapsed: false },
      { id: 'sa15', text: 'Dependency audit — zero high-severity CVEs',  state: 'unchecked', depth: 1, parentId: 'sa11', collapsed: false },
      { id: 'sa16', text: 'Logging & Monitoring',                        state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'sa17', text: 'Auth failures and rate limits logged',         state: 'unchecked', depth: 1, parentId: 'sa16', collapsed: false },
      { id: 'sa18', text: 'PII not written to logs',                     state: 'unchecked', depth: 1, parentId: 'sa16', collapsed: false },
      { id: 'sa19', text: 'Alerting configured for anomalous activity',  state: 'unchecked', depth: 1, parentId: 'sa16', collapsed: false },
    ],
  },
  {
    id: 'tpl-incident-postmortem',
    name: 'Incident Postmortem',
    description: 'Blameless postmortem checklist to document incidents, find root causes, and prevent recurrence.',
    category: 'security',
    mode: 'advanced',
    tags: ['postmortem', 'incident', 'blameless', 'root cause'],
    featured: true,
    previewLines: ['Incident Summary', 'Timeline of events documented', 'Root Cause', 'Contributing factors identified'],
    items: [
      { id: 'pm1',  text: 'Incident Summary',                             state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'pm2',  text: 'Incident title and severity recorded',         state: 'unchecked', depth: 1, parentId: 'pm1', collapsed: false },
      { id: 'pm3',  text: 'Start time, end time, duration noted',        state: 'unchecked', depth: 1, parentId: 'pm1', collapsed: false },
      { id: 'pm4',  text: 'Customer impact quantified',                  state: 'unchecked', depth: 1, parentId: 'pm1', collapsed: false },
      { id: 'pm5',  text: 'Timeline',                                    state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'pm6',  text: 'Chronological event timeline documented',     state: 'unchecked', depth: 1, parentId: 'pm5', collapsed: false },
      { id: 'pm7',  text: 'Detection method noted (alert vs customer)',  state: 'unchecked', depth: 1, parentId: 'pm5', collapsed: false },
      { id: 'pm8',  text: 'Each response action timestamped',           state: 'unchecked', depth: 1, parentId: 'pm5', collapsed: false },
      { id: 'pm9',  text: 'Root Cause Analysis',                        state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'pm10', text: 'Root cause identified (not just symptoms)',   state: 'unchecked', depth: 1, parentId: 'pm9', collapsed: false },
      { id: 'pm11', text: 'Contributing factors listed',                 state: 'unchecked', depth: 1, parentId: 'pm9', collapsed: false },
      { id: 'pm12', text: '5 Whys or similar analysis completed',       state: 'unchecked', depth: 1, parentId: 'pm9', collapsed: false },
      { id: 'pm13', text: 'Action Items',                               state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'pm14', text: 'Immediate fixes listed with owners',         state: 'unchecked', depth: 1, parentId: 'pm13', collapsed: false },
      { id: 'pm15', text: 'Long-term preventive actions defined',       state: 'unchecked', depth: 1, parentId: 'pm13', collapsed: false },
      { id: 'pm16', text: 'Monitoring improvements identified',         state: 'unchecked', depth: 1, parentId: 'pm13', collapsed: false },
      { id: 'pm17', text: 'Postmortem shared with stakeholders',        state: 'unchecked', depth: 1, parentId: 'pm13', collapsed: false },
    ],
  },
  {
    id: 'tpl-gdpr-compliance',
    name: 'GDPR Compliance Review',
    description: 'Practical GDPR compliance checklist for SaaS products handling EU personal data.',
    category: 'security',
    mode: 'simple',
    tags: ['gdpr', 'privacy', 'compliance', 'data protection'],
    featured: false,
    previewLines: ['Lawful basis for data processing documented', 'Privacy policy up to date and accessible', 'User data deletion request process exists', 'Data breach notification procedure defined'],
    items: [
      { id: 'gd1',  text: 'Lawful basis for each data processing activity documented', state: 'unchecked' },
      { id: 'gd2',  text: 'Privacy policy is current, clear, and accessible',          state: 'unchecked' },
      { id: 'gd3',  text: 'Cookie consent banner compliant (no pre-ticked boxes)',     state: 'unchecked' },
      { id: 'gd4',  text: 'Users can export their personal data',                      state: 'unchecked' },
      { id: 'gd5',  text: 'Users can request account and data deletion',               state: 'unchecked' },
      { id: 'gd6',  text: 'Data retention periods defined and enforced',               state: 'unchecked' },
      { id: 'gd7',  text: 'Third-party processors have DPAs in place',                state: 'unchecked' },
      { id: 'gd8',  text: 'Data transfers outside EU have legal mechanism (SCCs)',     state: 'unchecked' },
      { id: 'gd9',  text: 'Data breach notification procedure under 72h defined',      state: 'unchecked' },
      { id: 'gd10', text: 'DPO appointed or legal basis for exemption documented',    state: 'unchecked' },
      { id: 'gd11', text: 'Internal data processing register (Article 30) maintained', state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-pen-test-prep',
    name: 'Penetration Test Prep',
    description: 'Checklist to prepare your application and team for an external penetration test engagement.',
    category: 'security',
    mode: 'simple',
    tags: ['penetration test', 'pentest', 'security', 'preparation'],
    featured: false,
    previewLines: ['Scope and rules of engagement agreed in writing', 'Test environment isolated from production', 'Monitoring alerts suppressed for test IPs', 'Emergency contact list shared with testers'],
    items: [
      { id: 'pt1',  text: 'Scope of test agreed and documented in writing',         state: 'unchecked' },
      { id: 'pt2',  text: 'Rules of engagement signed by all parties',             state: 'unchecked' },
      { id: 'pt3',  text: 'Test environment isolated from production',             state: 'unchecked' },
      { id: 'pt4',  text: 'Test accounts with appropriate roles created',          state: 'unchecked' },
      { id: 'pt5',  text: 'WAF and rate limiting configured for test IPs',        state: 'unchecked' },
      { id: 'pt6',  text: 'Monitoring alert suppression for tester IP range',     state: 'unchecked' },
      { id: 'pt7',  text: 'Emergency contact list shared with testing team',       state: 'unchecked' },
      { id: 'pt8',  text: 'Legal counsel informed and signed off',                state: 'unchecked' },
      { id: 'pt9',  text: 'Network diagrams and architecture docs shared',        state: 'unchecked' },
      { id: 'pt10', text: 'Remediation SLA agreed for critical findings',         state: 'unchecked' },
    ],
  },
]
