import type { ChecklistTemplate } from './types'

export const startupTemplates: ChecklistTemplate[] = [
  {
    id: 'tpl-saas-launch',
    name: 'SaaS Launch',
    description: 'End-to-end launch checklist for taking a SaaS product from private beta to public.',
    category: 'startup',
    mode: 'advanced',
    tags: ['saas', 'launch', 'startup', 'go-to-market'],
    featured: true,
    previewLines: ['Product', 'Onboarding flow tested end-to-end', 'Growth', 'Pricing page live with clear CTA'],
    items: [
      { id: 'sl1',  text: 'Product',                                       state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'sl2',  text: 'Core feature set complete and stable',          state: 'unchecked', depth: 1, parentId: 'sl1', collapsed: false },
      { id: 'sl3',  text: 'Onboarding flow tested end-to-end',            state: 'unchecked', depth: 1, parentId: 'sl1', collapsed: false },
      { id: 'sl4',  text: 'Error tracking (Sentry/Datadog) configured',   state: 'unchecked', depth: 1, parentId: 'sl1', collapsed: false },
      { id: 'sl5',  text: 'Uptime monitoring enabled',                    state: 'unchecked', depth: 1, parentId: 'sl1', collapsed: false },
      { id: 'sl6',  text: 'Growth & Revenue',                             state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'sl7',  text: 'Pricing page live with clear CTA',             state: 'unchecked', depth: 1, parentId: 'sl6', collapsed: false },
      { id: 'sl8',  text: 'Stripe or payment processor integrated',       state: 'unchecked', depth: 1, parentId: 'sl6', collapsed: false },
      { id: 'sl9',  text: 'Free trial or freemium tier configured',       state: 'unchecked', depth: 1, parentId: 'sl6', collapsed: false },
      { id: 'sl10', text: 'Referral or affiliate mechanism in place',     state: 'unchecked', depth: 1, parentId: 'sl6', collapsed: false },
      { id: 'sl11', text: 'Legal & Compliance',                           state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'sl12', text: 'Terms of service published',                   state: 'unchecked', depth: 1, parentId: 'sl11', collapsed: false },
      { id: 'sl13', text: 'Privacy policy published and GDPR-ready',      state: 'unchecked', depth: 1, parentId: 'sl11', collapsed: false },
      { id: 'sl14', text: 'Cookie consent implemented',                   state: 'unchecked', depth: 1, parentId: 'sl11', collapsed: false },
      { id: 'sl15', text: 'Launch',                                       state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'sl16', text: 'Product Hunt submission scheduled',            state: 'unchecked', depth: 1, parentId: 'sl15', collapsed: false },
      { id: 'sl17', text: 'Launch announcement emails queued',            state: 'unchecked', depth: 1, parentId: 'sl15', collapsed: false },
      { id: 'sl18', text: 'Support channel (Intercom/Crisp) live',        state: 'unchecked', depth: 1, parentId: 'sl15', collapsed: false },
    ],
  },
  {
    id: 'tpl-product-hunt-launch',
    name: 'Product Hunt Launch',
    description: 'Day-by-day checklist to maximise your Product Hunt launch ranking and upvotes.',
    category: 'startup',
    mode: 'advanced',
    tags: ['product hunt', 'launch', 'growth', 'marketing'],
    featured: true,
    previewLines: ['Week Before', 'Maker profile complete with photo', 'Launch Day', 'Post live by 12:01am PT'],
    items: [
      { id: 'ph1',  text: 'Week Before',                                  state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ph2',  text: 'Maker profile complete with photo and bio',    state: 'unchecked', depth: 1, parentId: 'ph1', collapsed: false },
      { id: 'ph3',  text: 'Gallery screenshots and demo GIF ready',      state: 'unchecked', depth: 1, parentId: 'ph1', collapsed: false },
      { id: 'ph4',  text: 'Tagline A/B tested with 5+ people',           state: 'unchecked', depth: 1, parentId: 'ph1', collapsed: false },
      { id: 'ph5',  text: 'Hunter or self-hunt decided',                 state: 'unchecked', depth: 1, parentId: 'ph1', collapsed: false },
      { id: 'ph6',  text: 'Supporter list DM\'d with launch date',       state: 'unchecked', depth: 1, parentId: 'ph1', collapsed: false },
      { id: 'ph7',  text: 'Launch Day',                                   state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ph8',  text: 'Post live by 12:01am PT',                     state: 'unchecked', depth: 1, parentId: 'ph7', collapsed: false },
      { id: 'ph9',  text: 'First comment posted by maker with context',  state: 'unchecked', depth: 1, parentId: 'ph7', collapsed: false },
      { id: 'ph10', text: 'Launch tweet and LinkedIn post published',     state: 'unchecked', depth: 1, parentId: 'ph7', collapsed: false },
      { id: 'ph11', text: 'Email blast sent to waitlist',                state: 'unchecked', depth: 1, parentId: 'ph7', collapsed: false },
      { id: 'ph12', text: 'Reply to every comment within 1 hour',        state: 'unchecked', depth: 1, parentId: 'ph7', collapsed: false },
      { id: 'ph13', text: 'Post-Launch',                                  state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ph14', text: 'Thank-you comment posted at end of day',      state: 'unchecked', depth: 1, parentId: 'ph13', collapsed: false },
      { id: 'ph15', text: 'Metrics (signups, revenue) captured',         state: 'unchecked', depth: 1, parentId: 'ph13', collapsed: false },
      { id: 'ph16', text: 'Follow-up email to new users sent',           state: 'unchecked', depth: 1, parentId: 'ph13', collapsed: false },
    ],
  },
  {
    id: 'tpl-investor-pitch',
    name: 'Investor Pitch Prep',
    description: 'Checklist to prepare a compelling investor pitch deck and data room for fundraising.',
    category: 'startup',
    mode: 'simple',
    tags: ['fundraising', 'pitch deck', 'investor', 'startup'],
    featured: false,
    previewLines: ['Problem and solution slides clear and concise', 'Traction metrics up to date', 'Financial model with 3-year projections', 'Data room with cap table and financials ready'],
    items: [
      { id: 'ip1',  text: 'Problem slide — pain is clear and quantified',        state: 'unchecked' },
      { id: 'ip2',  text: 'Solution slide — value prop in one sentence',          state: 'unchecked' },
      { id: 'ip3',  text: 'Market size — TAM/SAM/SOM with sources',              state: 'unchecked' },
      { id: 'ip4',  text: 'Traction — MRR, DAU, churn, growth rate current',     state: 'unchecked' },
      { id: 'ip5',  text: 'Business model — how you make money is obvious',       state: 'unchecked' },
      { id: 'ip6',  text: 'Go-to-market strategy slide',                          state: 'unchecked' },
      { id: 'ip7',  text: 'Competition landscape — honest differentiation',       state: 'unchecked' },
      { id: 'ip8',  text: 'Team slide — relevant experience highlighted',         state: 'unchecked' },
      { id: 'ip9',  text: 'Financial model — 3-year projections with assumptions', state: 'unchecked' },
      { id: 'ip10', text: 'Ask slide — raise amount and use of funds clear',      state: 'unchecked' },
      { id: 'ip11', text: 'Data room: cap table, incorporation docs, financials', state: 'unchecked' },
      { id: 'ip12', text: 'Deck reviewed by a founder who has raised before',     state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-mvp-scope',
    name: 'MVP Scope Definition',
    description: 'Structured checklist to define, validate, and lock MVP scope before development begins.',
    category: 'startup',
    mode: 'simple',
    tags: ['mvp', 'product', 'scope', 'validation'],
    featured: false,
    previewLines: ['Core problem and target user defined', 'Riskiest assumption identified', 'Success metric agreed before building', 'Features outside MVP written down and parked'],
    items: [
      { id: 'mv1',  text: 'Core problem statement written in one sentence',       state: 'unchecked' },
      { id: 'mv2',  text: 'Target user persona defined (not "everyone")',         state: 'unchecked' },
      { id: 'mv3',  text: 'Riskiest assumption identified and named',             state: 'unchecked' },
      { id: 'mv4',  text: 'Minimum success metric agreed before building',        state: 'unchecked' },
      { id: 'mv5',  text: 'User interviewed (at least 5 conversations)',          state: 'unchecked' },
      { id: 'mv6',  text: 'Feature list written and prioritised',                 state: 'unchecked' },
      { id: 'mv7',  text: 'Out-of-scope features parked in a backlog',           state: 'unchecked' },
      { id: 'mv8',  text: 'Build vs buy vs no-code decision made for each part', state: 'unchecked' },
      { id: 'mv9',  text: 'Launch timeline set with hard deadline',               state: 'unchecked' },
      { id: 'mv10', text: 'Stakeholders aligned on scope in writing',             state: 'unchecked' },
    ],
  },
]
