import type { ChecklistTemplate } from './types'

export const studyTemplates: ChecklistTemplate[] = [
  {
    id: 'tpl-exam-prep',
    name: 'Exam Preparation',
    description: 'Structured exam prep checklist to cover material systematically and walk in confident.',
    category: 'study',
    mode: 'advanced',
    tags: ['exam', 'study', 'revision', 'student'],
    featured: true,
    previewLines: ['4 Weeks Out', 'Full syllabus mapped to topics', 'Final Week', 'Past papers completed under timed conditions'],
    items: [
      { id: 'ep1',  text: '4 Weeks Out',                                      state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ep2',  text: 'Obtain full syllabus and past papers',             state: 'unchecked', depth: 1, parentId: 'ep1', collapsed: false },
      { id: 'ep3',  text: 'Map all topics — tick what you know vs don\'t',   state: 'unchecked', depth: 1, parentId: 'ep1', collapsed: false },
      { id: 'ep4',  text: 'Build a revision schedule with topic blocks',      state: 'unchecked', depth: 1, parentId: 'ep1', collapsed: false },
      { id: 'ep5',  text: 'Gather all notes, textbooks, and resources',      state: 'unchecked', depth: 1, parentId: 'ep1', collapsed: false },
      { id: 'ep6',  text: '2 Weeks Out',                                      state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ep7',  text: 'First pass through all topics complete',           state: 'unchecked', depth: 1, parentId: 'ep6', collapsed: false },
      { id: 'ep8',  text: 'Flashcards or summary notes created',             state: 'unchecked', depth: 1, parentId: 'ep6', collapsed: false },
      { id: 'ep9',  text: 'Weak areas identified and given extra time',      state: 'unchecked', depth: 1, parentId: 'ep6', collapsed: false },
      { id: 'ep10', text: 'Study group or accountability partner checked in', state: 'unchecked', depth: 1, parentId: 'ep6', collapsed: false },
      { id: 'ep11', text: 'Final Week',                                       state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ep12', text: 'At least 2 past papers done under timed conditions', state: 'unchecked', depth: 1, parentId: 'ep11', collapsed: false },
      { id: 'ep13', text: 'Marked past papers — errors reviewed not ignored', state: 'unchecked', depth: 1, parentId: 'ep11', collapsed: false },
      { id: 'ep14', text: 'Sleep 8h every night this week',                  state: 'unchecked', depth: 1, parentId: 'ep11', collapsed: false },
      { id: 'ep15', text: 'Exam Day',                                         state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'ep16', text: 'Exam location, time, and ID confirmed',           state: 'unchecked', depth: 1, parentId: 'ep15', collapsed: false },
      { id: 'ep17', text: 'Allowed materials packed (pens, calculator, ID)', state: 'unchecked', depth: 1, parentId: 'ep15', collapsed: false },
      { id: 'ep18', text: 'Arrive 15 minutes early',                         state: 'unchecked', depth: 1, parentId: 'ep15', collapsed: false },
    ],
  },
  {
    id: 'tpl-study-plan',
    name: 'Weekly Study Plan',
    description: 'Weekly study planning checklist to balance subjects, avoid burnout, and make measurable progress.',
    category: 'study',
    mode: 'simple',
    tags: ['study plan', 'weekly', 'student', 'time management'],
    featured: true,
    previewLines: ['Review last week — what did I actually complete?', 'List subjects and topics to cover this week', 'Assign specific sessions to calendar blocks', 'Set one measurable goal per subject'],
    items: [
      { id: 'wp1',  text: 'Review last week — what did I actually complete?',     state: 'unchecked' },
      { id: 'wp2',  text: 'List all subjects and topics due this week',            state: 'unchecked' },
      { id: 'wp3',  text: 'Prioritise by deadline and difficulty',                state: 'unchecked' },
      { id: 'wp4',  text: 'Assign topics to specific time blocks in calendar',    state: 'unchecked' },
      { id: 'wp5',  text: 'Set one measurable goal per subject (not "study maths")', state: 'unchecked' },
      { id: 'wp6',  text: 'Plan breaks — Pomodoro or 50/10 intervals',           state: 'unchecked' },
      { id: 'wp7',  text: 'Identify any gaps: missing notes, overdue reading',   state: 'unchecked' },
      { id: 'wp8',  text: 'Protect at least one full rest period this week',      state: 'unchecked' },
      { id: 'wp9',  text: 'Share plan with accountability partner or study group', state: 'unchecked' },
      { id: 'wp10', text: 'End of week: mark what was done and reflect',          state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-micro-learning',
    name: 'Micro-Learning Session',
    description: 'Focused 25-minute learning session checklist for mastering one concept at a time.',
    category: 'study',
    mode: 'simple',
    tags: ['micro-learning', 'focus', 'pomodoro', 'skill building'],
    featured: false,
    previewLines: ['Write the one concept to learn in this session', 'Remove all distractions before starting', 'Summarise in your own words after reading', 'Create one flashcard or recall question'],
    items: [
      { id: 'ml1', text: 'Write the single concept to learn this session',       state: 'unchecked' },
      { id: 'ml2', text: 'Remove distractions — phone away, tabs closed',       state: 'unchecked' },
      { id: 'ml3', text: 'Set a 25-minute timer',                               state: 'unchecked' },
      { id: 'ml4', text: 'Read or watch source material once without notes',    state: 'unchecked' },
      { id: 'ml5', text: 'Summarise the concept in your own words',             state: 'unchecked' },
      { id: 'ml6', text: 'Identify what you still don\'t understand',          state: 'unchecked' },
      { id: 'ml7', text: 'Create one flashcard or recall question',             state: 'unchecked' },
      { id: 'ml8', text: 'Link concept to something you already know',          state: 'unchecked' },
      { id: 'ml9', text: 'Add to spaced-repetition deck (Anki / Notion)',       state: 'unchecked' },
    ],
  },
  {
    id: 'tpl-research-paper',
    name: 'Research Paper Writing',
    description: 'Step-by-step checklist for researching, structuring, and submitting an academic paper.',
    category: 'study',
    mode: 'advanced',
    tags: ['research', 'academic writing', 'essay', 'thesis'],
    featured: false,
    previewLines: ['Research', 'Research question clearly stated', 'Writing', 'Argument flows logically between paragraphs'],
    items: [
      { id: 'rp1',  text: 'Research',                                           state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'rp2',  text: 'Research question or thesis statement defined',      state: 'unchecked', depth: 1, parentId: 'rp1', collapsed: false },
      { id: 'rp3',  text: 'At least 10 credible sources gathered',             state: 'unchecked', depth: 1, parentId: 'rp1', collapsed: false },
      { id: 'rp4',  text: 'Sources saved with full citation details',           state: 'unchecked', depth: 1, parentId: 'rp1', collapsed: false },
      { id: 'rp5',  text: 'Notes annotated with page numbers',                 state: 'unchecked', depth: 1, parentId: 'rp1', collapsed: false },
      { id: 'rp6',  text: 'Structure',                                          state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'rp7',  text: 'Outline with section headings created',             state: 'unchecked', depth: 1, parentId: 'rp6', collapsed: false },
      { id: 'rp8',  text: 'Argument mapped — each paragraph has one point',   state: 'unchecked', depth: 1, parentId: 'rp6', collapsed: false },
      { id: 'rp9',  text: 'Counterarguments acknowledged and addressed',       state: 'unchecked', depth: 1, parentId: 'rp6', collapsed: false },
      { id: 'rp10', text: 'Writing & Review',                                  state: 'unchecked', depth: 0, parentId: null,  collapsed: false },
      { id: 'rp11', text: 'First draft written without self-editing',          state: 'unchecked', depth: 1, parentId: 'rp10', collapsed: false },
      { id: 'rp12', text: 'Argument flows logically paragraph to paragraph',  state: 'unchecked', depth: 1, parentId: 'rp10', collapsed: false },
      { id: 'rp13', text: 'Plagiarism check run',                              state: 'unchecked', depth: 1, parentId: 'rp10', collapsed: false },
      { id: 'rp14', text: 'Citations formatted correctly (APA/MLA/Chicago)',   state: 'unchecked', depth: 1, parentId: 'rp10', collapsed: false },
      { id: 'rp15', text: 'Proofread by a peer or read aloud',                state: 'unchecked', depth: 1, parentId: 'rp10', collapsed: false },
      { id: 'rp16', text: 'Submitted before deadline with confirmation saved', state: 'unchecked', depth: 1, parentId: 'rp10', collapsed: false },
    ],
  },
]
